"""Tests for TaskQ.watch_reclaims() and its transport helpers
(_watch_reclaims_poll, _watch_reclaims_pg).

Unit tests run with ``pytest -m "not integration"`` — no Docker — using
:class:`InMemoryBackend`, following the pattern already established in
test_stream.py for TaskQ.stream().

Integration tests require Docker/testcontainers and are individually
decorated with ``@pytest.mark.integration``.

Covers:
- Poll-only transport (no DSN/listen source): events are yielded in
  ascending event_id order; the poll_timeout sleep branch is exercised
  when nothing new is available; resumption via after_id does not
  re-yield already-seen events.
- PG LISTEN transport: a real crash-reclaim is delivered promptly
  (NOTIFY-driven), not merely eventually via the poll-timeout fallback.
- Chaos — the LISTEN connection is killed mid-stream (pg_terminate_backend,
  same technique as test_stream.py's PG-LISTEN chaos test); the generator
  falls back to polling and keeps delivering correctly.
"""

# ruff: noqa: S608 Why: schema name is generated by new_base62()/validated by
# the migration runner's _IDENT_RE; asyncpg has no parameter binding for
# identifiers. Same suppression as test_stream.py.

import asyncio
import shutil
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import UUID

import asyncpg
import pytest

from taskq._ids import new_base62, new_uuid
from taskq.backend._protocol import EventRow, JobId
from taskq.client._jobs import JobsClient
from taskq.client._taskq import TaskQ
from taskq.settings import TaskQSettings
from taskq.testing.clock import FakeClock
from taskq.testing.in_memory import InMemoryBackend
from taskq.testing.jobs import make_enqueue_args

_UNIT_SCHEMA_LABEL = "taskq_test"
_START = datetime(2025, 1, 1, tzinfo=UTC)
_GRACE = timedelta(seconds=30)


def _make_backend() -> InMemoryBackend:
    return InMemoryBackend(clock=FakeClock(start=_START))


def _make_client(backend: InMemoryBackend) -> JobsClient:
    settings = TaskQSettings.load_from_dict({"TASKQ_SCHEMA_NAME": _UNIT_SCHEMA_LABEL})
    return JobsClient(backend, settings=settings)


def _inject_poll_only_tq(backend: InMemoryBackend, *, poll_timeout: float = 30.0) -> TaskQ:
    """Construct a TaskQ with no DSN/listen source, forcing watch_reclaims()
    onto the plain poll loop — mirrors test_stream.py's _inject_tq, but sets
    every transport-selecting attribute explicitly since watch_reclaims()
    (unlike stream() on a terminal/missing job) always reaches the
    transport-dispatch branch.
    """
    tq = TaskQ.__new__(TaskQ)
    tq._dsn = None
    tq._pool = None
    tq._schema = _UNIT_SCHEMA_LABEL
    tq._min_pool_size = 1
    tq._max_pool_size = 5
    tq._redis_url = None
    tq._redis_client = None
    tq._pg_conn_factory = None
    tq._listen_conn = None
    tq._poll_timeout = poll_timeout
    tq._owns_pool = True
    tq._client = _make_client(backend)
    return tq


async def _make_running_row(
    backend: InMemoryBackend,
    *,
    max_attempts: int = 3,
    retry_kind: str = "transient",
) -> JobId:
    """Enqueue a job and manually flip it to running with an expired lock,
    then reclaim it — leaves one crash-reclaim event in the backend's
    event log for watch_reclaims()/poll_reclaim_events() to observe.
    """
    from dataclasses import replace as _replace

    args = make_enqueue_args(
        actor="watch_reclaims_test_actor",
        queue="default",
        payload={},
        scheduled_at=_START,
        max_attempts=max_attempts,
        retry_kind=retry_kind,  # type: ignore[arg-type]  # Why: test helper accepts the same RetryKind literals as the real EnqueueArgs
        priority=0,
        schedule_to_close=None,
    )
    row = await backend.enqueue(args)
    job_id = row.id

    worker_id = backend._worker_id  # type: ignore[reportPrivateUsage]  # Why: test-only private access
    running_row = _replace(
        row,
        status="running",
        locked_by_worker=worker_id,
        lock_expires_at=_START - timedelta(seconds=1),
        started_at=_START,
        last_heartbeat_at=_START,
    )
    backend._jobs[job_id] = running_row  # type: ignore[reportPrivateUsage]  # Why: test-only private access

    count = await backend.reclaim_expired_locks(_START + timedelta(seconds=1), _GRACE, _GRACE)
    assert count == 1
    return job_id


async def _collect(gen: Any, *, n: int) -> list[EventRow]:
    """Collect exactly *n* items from an unbounded async generator, then
    stop iterating (closing it via aclosing semantics). Callers wrap this
    in ``asyncio.wait_for`` for an overall deadline."""
    import contextlib

    collected: list[EventRow] = []
    async with contextlib.aclosing(gen) as agen:
        async for evt in agen:
            collected.append(evt)
            if len(collected) >= n:
                break
    return collected


# ── Poll-only transport (unit, no Docker) ──────────────────────────


async def test_watch_reclaims_poll_only_yields_ascending() -> None:
    """No DSN/listen source: watch_reclaims() falls back to the plain
    poll loop and yields crash-reclaim events in ascending event_id
    order."""
    backend = _make_backend()
    await _make_running_row(backend)
    await _make_running_row(backend)

    tq = _inject_poll_only_tq(backend, poll_timeout=0.05)
    events = await asyncio.wait_for(_collect(tq.watch_reclaims(after_id=0), n=2), timeout=5.0)

    assert len(events) == 2
    assert events[0].event_id < events[1].event_id
    assert all(e.detail["reason"] == "lock_expired" for e in events)


async def test_watch_reclaims_poll_timeout_sleep_branch() -> None:
    """When nothing new is available, the poll loop sleeps for
    poll_timeout before checking again — exercised by starting with an
    empty backend and asserting no event arrives until one is created
    after the first sleep would have elapsed."""
    backend = _make_backend()
    tq = _inject_poll_only_tq(backend, poll_timeout=0.05)

    gen = tq.watch_reclaims(after_id=0)

    async def _produce_after_delay() -> None:
        await asyncio.sleep(0.15)
        await _make_running_row(backend)

    producer = asyncio.create_task(_produce_after_delay())
    try:
        events = await asyncio.wait_for(_collect(gen, n=1), timeout=5.0)
        assert len(events) == 1
    finally:
        await producer


async def test_watch_reclaims_resumption_does_not_replay() -> None:
    """Calling watch_reclaims(after_id=N) after a previous call yielded up
    to event_id N must not re-yield events with event_id <= N."""
    backend = _make_backend()
    await _make_running_row(backend)
    await _make_running_row(backend)

    tq = _inject_poll_only_tq(backend, poll_timeout=0.05)

    first_batch = await asyncio.wait_for(_collect(tq.watch_reclaims(after_id=0), n=2), timeout=5.0)
    assert len(first_batch) == 2
    last_seen = first_batch[-1].event_id

    await _make_running_row(backend)

    second_batch = await asyncio.wait_for(
        _collect(tq.watch_reclaims(after_id=last_seen), n=1), timeout=5.0
    )
    assert len(second_batch) == 1
    assert second_batch[0].event_id > last_seen
    assert all(e.event_id > last_seen for e in second_batch)


# ── PG LISTEN transport + chaos (integration, Docker) ──────────────


async def _open_taskq_pg(
    pg_dsn: str,
    *,
    schema: str,
    poll_timeout: float = 5.0,
) -> tuple[TaskQ, UUID]:
    """Open a TaskQ against the PG container with schema isolation.

    Mirrors test_stream.py's helper of the same name.
    """
    from taskq.migrate import apply_pending

    conn = await asyncpg.connect(pg_dsn)
    try:
        await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
        await apply_pending(conn, schema=schema)
    finally:
        await conn.close()

    tq = TaskQ(dsn=pg_dsn, schema=schema, poll_timeout=poll_timeout)
    await tq.open()

    worker_id = new_uuid()
    assert tq._client is not None
    async with tq._pool.acquire() as c:  # type: ignore[union-attr] # Why: tq._pool is set by open()
        await c.execute(
            f'INSERT INTO "{schema}".workers (id, hostname, pid, queues) '
            "VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO NOTHING",
            worker_id,
            "test-host",
            12345,
            ["default"],
        )
    return tq, worker_id


@pytest.mark.integration
async def test_watch_reclaims_pg_listen_delivers_promptly(pg_dsn: str) -> None:
    """A real crash-reclaim (force-expired lock + Sweep 1) is delivered
    via watch_reclaims() well before poll_timeout would have elapsed on
    its own — i.e. the NOTIFY-driven wakeup (plus its bounded post-notify
    catch-up poll, which bridges RECLAIM_EVENT_VISIBILITY_DELAY), not
    just the poll-timeout fallback, is what delivered it. poll_timeout is
    deliberately large (30s, TaskQ's real default) so that a poll-only
    fallback would clearly not have delivered this quickly."""
    from taskq.backend.postgres import PostgresBackend
    from taskq.testing.pg import create_running_job

    schema = f"tst_{new_base62()}".lower()
    tq, worker_id = await _open_taskq_pg(pg_dsn, schema=schema, poll_timeout=30.0)
    try:
        assert tq._pool is not None
        async with tq._pool.acquire() as conn:
            # _open_taskq_pg already inserted the worker row for worker_id.
            job_id = await create_running_job(
                conn,
                schema,
                worker_id,
                lock_expires_at=datetime.now(UTC) - timedelta(seconds=10),
                max_attempts=1,
                retry_kind="transient",
                attempt=1,
            )

        loop_start = asyncio.get_event_loop().time()

        async def _sweep_soon() -> None:
            await asyncio.sleep(0.2)
            assert tq._pool is not None
            async with tq._pool.acquire() as conn:
                await PostgresBackend.sweep_expired_locks(
                    conn,
                    datetime.now(UTC),
                    _GRACE,
                    _GRACE,
                    schema=schema,
                )

        sweep_task = asyncio.create_task(_sweep_soon())
        try:
            events = await asyncio.wait_for(
                _collect(tq.watch_reclaims(after_id=0), n=1), timeout=8.0
            )
        finally:
            await sweep_task

        elapsed = asyncio.get_event_loop().time() - loop_start
        assert len(events) == 1
        assert events[0].job_id == JobId(job_id)
        # Comfortably under poll_timeout (30s) — proves NOTIFY plus its
        # bounded catch-up poll delivered this, not the poll-timeout
        # fallback alone (which would have taken ~30s).
        assert elapsed < 6.0
    finally:
        await tq.close()


@pytest.mark.integration
async def test_watch_reclaims_survives_listen_connection_kill(pg_dsn: str) -> None:
    """pg_terminate_backend kills watch_reclaims()'s dedicated LISTEN
    connection mid-stream (same technique as test_stream.py's
    test_tc1_pg_listen_connection_dropped_stream_recovers); the generator
    does not propagate an unhandled exception and keeps delivering
    correctly via the poll-timeout fallback."""
    from taskq.backend.postgres import PostgresBackend
    from taskq.testing.pg import create_running_job

    schema = f"tst_{new_base62()}".lower()
    tq, worker_id = await _open_taskq_pg(pg_dsn, schema=schema, poll_timeout=0.3)
    try:
        assert tq._pool is not None
        # _open_taskq_pg already inserted the worker row for worker_id.

        gen = tq.watch_reclaims(after_id=0)

        # Start consuming in the background so the LISTEN connection is
        # actually opened before we kill it.
        collect_task = asyncio.create_task(asyncio.wait_for(_collect(gen, n=1), timeout=10.0))
        await asyncio.sleep(0.2)

        assert tq._pool is not None
        async with tq._pool.acquire() as conn:
            listen_pids = await conn.fetch(
                "SELECT pid FROM pg_stat_activity "
                "WHERE query LIKE '%LISTEN%' AND datname = current_database() "
                "AND pid != pg_backend_pid()"
            )
        psql_path = shutil.which("psql")
        assert psql_path is not None, "psql not found on PATH"
        for row in listen_pids:
            proc = await asyncio.create_subprocess_exec(
                psql_path,
                pg_dsn,
                "-c",
                f"SELECT pg_terminate_backend({int(row['pid'])})",
                stdout=asyncio.subprocess.DEVNULL,
                stderr=asyncio.subprocess.DEVNULL,
            )
            await proc.wait()

        await asyncio.sleep(0.3)

        # Now produce the crash-reclaim event; the poll-fallback loop
        # (not the dead LISTEN connection) must still pick it up.
        async with tq._pool.acquire() as conn:
            job_id = await create_running_job(
                conn,
                schema,
                worker_id,
                lock_expires_at=datetime.now(UTC) - timedelta(seconds=10),
                max_attempts=1,
                retry_kind="transient",
                attempt=1,
            )
            await PostgresBackend.sweep_expired_locks(
                conn,
                datetime.now(UTC),
                _GRACE,
                _GRACE,
                schema=schema,
            )

        events = await collect_task
        assert len(events) == 1
        assert events[0].job_id == JobId(job_id)
    finally:
        await tq.close()
