# ruff: noqa: S608  # Why: every interpolated identifier is generated by this file (schema, role) and validated/parameter-safe by construction; every value is $-bound.
"""Pin: a leader that dies WITHOUT a FIN must lose the role on the lease
horizon, to a follower holding no special privilege.

The failure this file watches: the holder's TCP session dies without a FIN
(power loss, SIGSTOP, a black-holed partition), so nothing at the server
closes it. Leadership is the row lease in ``maintenance_leader`` - the
holder's own ``expires_at`` is the horizon, and takeover is an UPDATE any
application role may run - so recovery needs neither the server's
connection reaping (stock keepalives: ~2 h 11 m) nor the privilege to
terminate another backend (commonly reserved on managed Postgres).

The proof shape: pod A is frozen mid-leadership with every connection held
open - the no-FIN shape - and pod B runs as a freshly created
``NOSUPERUSER`` role whose inability to terminate a peer's backend is
asserted against the live server before the freeze. B must promote within
``leader_lease + heartbeat_interval + margin``, the maintenance_leader row
must come to name B, and no terminate-based reclaim may be issued - the
mechanism that needed the privilege is gone, and the promotion must not
depend on it.
"""

from __future__ import annotations

import asyncio
import contextlib
import logging
from contextlib import AsyncExitStack
from datetime import timedelta
from urllib.parse import urlsplit, urlunsplit
from uuid import UUID

import asyncpg
import pytest

from taskq._ids import new_base62, new_uuid
from taskq.backend.clock import SystemClock
from taskq.backend.postgres import PostgresBackend
from taskq.migrate import apply_pending
from taskq.obs import setup_logging
from taskq.settings import WorkerSettings
from taskq.testing.assertions import wait_for_condition
from taskq.testing.fixtures import _create_worker
from taskq.testing.settings import shorten_chaos_settings
from taskq.worker.deps import WorkerDeps, open_worker_deps
from taskq.worker.leader import MaintenanceLeader

pytestmark = pytest.mark.integration

#: Slack past the lease horizon for the follower's next election tick, the
#: round trips, and scheduling jitter. The bound being pinned is
#: ``resolved_leader_lease + heartbeat_interval``; this is the margin over
#: it, not a second horizon.
_RECOVERY_SLACK_SECS: float = 3.0


async def _election_only(
    deps: WorkerDeps, backend: PostgresBackend, worker_id: UUID
) -> tuple[MaintenanceLeader, asyncio.Event, asyncio.Task[None]]:
    """Start ONLY the leader's election loop - no ``run()`` TaskGroup, no watchdog.

    Starting the election loop alone lets this file freeze a REAL elected
    leader in place (stop the loop task, keep every connection open) - the
    no-FIN holder shape - without tearing its session down.
    """
    leader = MaintenanceLeader(deps, worker_id, backend, clock=SystemClock())
    shutdown = asyncio.Event()
    task = asyncio.create_task(
        leader._election_loop(shutdown),  # pyright: ignore[reportPrivateUsage]  # Why: the harness contract starts individual leader loops by hand; the election loop alone is the seam under test.
        name=f"rt-election-{worker_id}",
    )
    return leader, shutdown, task


async def _stop_election_task(
    task: asyncio.Task[None], shutdown: asyncio.Event, heartbeat: float
) -> None:
    """Stop an election-loop task: shutdown wakes it within one heartbeat."""
    shutdown.set()
    try:
        await asyncio.wait_for(task, timeout=heartbeat + 5.0)
    except TimeoutError:
        task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await task


async def _release_leader_conns(leader: MaintenanceLeader) -> None:
    """Close the leader-owned conns (cron/monitor/leader) the election-only
    startup path leaves open - ``run()``'s finally normally does this."""
    await leader._close_leader_owned_conns(mid_run=False)  # pyright: ignore[reportPrivateUsage]  # Why: election-only startup skips run()'s teardown; this is its manual equivalent.
    await leader._drop_leader_conn(reason="rt teardown")  # pyright: ignore[reportPrivateUsage]  # Why: same - release the session's courtesy lock for teardown.


async def _open_pod(
    pg_dsn: str, schema: str
) -> tuple[AsyncExitStack, WorkerDeps, PostgresBackend, UUID]:
    """Open one worker's deps + backend against an already-migrated schema,
    on whatever DSN the caller hands in - the follower in this file connects
    as the restricted role, so its whole connection surface inherits the
    restriction the way a deployment's pod would."""
    settings = WorkerSettings.load_from_dict({"pg_dsn": pg_dsn, "schema_name": schema})
    stack = AsyncExitStack()
    deps: WorkerDeps = await stack.enter_async_context(open_worker_deps(settings))
    try:
        backend = PostgresBackend(
            deps,
            clock=SystemClock(),
            cancellation_grace_period=timedelta(seconds=deps.settings.cancellation_grace_period),
            cleanup_grace_period=timedelta(seconds=deps.settings.cleanup_grace_period),
        )
    except BaseException:
        await stack.aclose()
        raise
    worker_id = new_uuid()
    async with deps.dispatcher_pool.acquire() as conn:
        await _create_worker(conn, settings.schema_name, worker_id)
    return stack, deps, backend, worker_id


async def test_no_fin_leader_death_leadership_must_be_recoverable_within_bounded_window(
    pg_dsn: str, caplog: pytest.LogCaptureFixture
) -> None:
    schema = f"tlrt_{new_base62()}".lower()
    role = f"tqnsu_{new_base62(10)}".lower()
    # Generated per run and base62 (alphanumeric), so the DDL literal below
    # cannot break out of its quotes; nothing secret is hardcoded - the
    # credential exists only inside the throwaway test container.
    role_password = new_base62(24)

    admin = await asyncpg.connect(pg_dsn)
    try:
        await admin.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
        await apply_pending(admin, schema=schema)
        await admin.execute(f"CREATE ROLE {role} LOGIN NOSUPERUSER PASSWORD '{role_password}'")
        await admin.execute(f'GRANT USAGE ON SCHEMA "{schema}" TO {role}')
        await admin.execute(
            f'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "{schema}" TO {role}'
        )
    finally:
        await admin.close()

    parts = urlsplit(pg_dsn)
    role_dsn = urlunsplit(
        parts._replace(netloc=f"{role}:{role_password}@{parts.hostname}:{parts.port}")
    )

    stack_a: AsyncExitStack | None = None
    stack_b: AsyncExitStack | None = None
    leader_a: MaintenanceLeader | None = None
    leader_b: MaintenanceLeader | None = None
    task_b: asyncio.Task[None] | None = None
    shutdown_b: asyncio.Event | None = None
    try:
        # The environment premise, proven against the live server before the
        # scenario runs: the follower's role is not a superuser and cannot
        # terminate another session's backend. Without this proof the test
        # would silently exercise a deployment shape it claims to forbid.
        probe = await asyncpg.connect(role_dsn)
        try:
            rolsuper = await probe.fetchval(
                "SELECT rolsuper FROM pg_roles WHERE rolname = current_user"
            )
            assert rolsuper is False, "the follower role must not be a superuser"
        finally:
            await probe.close()

        stack_a, deps_a, backend_a, wid_a = await _open_pod(pg_dsn, schema)
        stack_b, deps_b, backend_b, wid_b = await _open_pod(role_dsn, schema)

        with shorten_chaos_settings(deps_a, deps_b):
            heartbeat = deps_a.settings.heartbeat_interval
            recovery_window = (
                deps_a.settings.resolved_leader_lease + heartbeat + _RECOVERY_SLACK_SECS
            )

            leader_a, shutdown_a, task_a = await _election_only(deps_a, backend_a, wid_a)
            try:
                # A real leader wins the election and holds the lease.
                await asyncio.wait_for(deps_a.is_leader.wait(), timeout=2 * heartbeat + 5.0)
                assert deps_a.leader_conn is not None and not deps_a.leader_conn.is_closed()

                # The privilege probe needs a live foreign backend: A's
                # leader conn is one. The restricted role must be refused.
                # (leader_conn is shared with the election loop's renewals;
                # retry past a "busy" race as tc1 does.)
                a_pid: int | None = None
                for _ in range(5):
                    try:
                        a_pid = await deps_a.leader_conn.fetchval("SELECT pg_backend_pid()")
                        break
                    except (asyncpg.InternalClientError, asyncpg.InterfaceError):
                        await asyncio.sleep(0.2)
                assert a_pid is not None, "failed to read the frozen-soon leader's backend pid"
                probe = await asyncpg.connect(role_dsn)
                try:
                    with pytest.raises(asyncpg.InsufficientPrivilegeError):
                        await probe.fetchval("SELECT pg_terminate_backend($1)", a_pid)
                finally:
                    await probe.close()

                # -- A dies WITHOUT a FIN ----------------------------------
                # Stopping ONLY the election-loop task exits the loop with no
                # cleanup: deps_a.leader_conn (and the cron/monitor conns) stay
                # OPEN and idle and is_leader stays SET - a holder gone silent
                # with its session alive. Nothing sends a FIN; from pod B's
                # side this is exactly a partitioned/black-holed leader.
                shutdown_a.set()
                await asyncio.wait_for(task_a, timeout=heartbeat + 5.0)
                assert deps_a.is_leader.is_set()
                assert deps_a.leader_conn is not None and not deps_a.leader_conn.is_closed()

                # -- B must take over on the lease horizon ----------------
                leader_b, shutdown_b, task_b = await _election_only(deps_b, backend_b, wid_b)
                # caplog over structlog.testing.capture_logs: the latter's
                # reach depends on which earlier test configured structlog,
                # so a log assertion built on it passes or fails by session
                # ordering. setup_logging is the production configurator and
                # idempotent, so this makes the routing explicit.
                setup_logging(level="DEBUG", log_format="json")
                with caplog.at_level(logging.DEBUG):
                    await wait_for_condition(
                        deps_b.is_leader.is_set,
                        description=(
                            "the restricted follower promoted within "
                            f"{recovery_window:.1f}s (resolved_leader_lease + "
                            f"heartbeat_interval + {_RECOVERY_SLACK_SECS}s slack) "
                            "of the holder going silent without a FIN"
                        ),
                        timeout=recovery_window,
                    )

                assert deps_b.is_leader.is_set()
                reclaims = [r for r in caplog.records if "leader-holder-reclaim" in r.getMessage()]
                assert reclaims == [], (
                    "recovery must not terminate the silent holder's backend: "
                    "that path needed a privilege the application role may not "
                    "hold, and it is gone"
                )

                async with deps_b.dispatcher_pool.acquire() as conn:
                    row = await conn.fetchrow(
                        f'SELECT worker_id FROM "{schema}".maintenance_leader '
                        f"WHERE singleton = true"
                    )
                assert row is not None, "promotion must record a maintenance_leader row"
                assert UUID(str(row["worker_id"])) == wid_b, (
                    "the maintenance_leader row must reflect the promoted pod's "
                    f"worker_id, got {row['worker_id']}"
                )
                assert any(
                    "leader-advisory-lock-unavailable" in r.getMessage() for r in caplog.records
                ), (
                    "the frozen holder's session still holds the courtesy lock, so "
                    "the takeover must show its miss - proof the election never "
                    "waited on it"
                )
            finally:
                if task_b is not None and shutdown_b is not None:
                    await _stop_election_task(task_b, shutdown_b, heartbeat)
                if leader_b is not None:
                    await _release_leader_conns(leader_b)
                await _release_leader_conns(leader_a)
    finally:
        if stack_b is not None:
            await stack_b.aclose()
        if stack_a is not None:
            await stack_a.aclose()
        admin = await asyncpg.connect(pg_dsn)
        try:
            await admin.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await admin.execute(f"DROP ROLE IF EXISTS {role}")
        finally:
            await admin.close()
