"""Tests for the enqueue_batch_fast COPY FROM primitive.

Unit tests run against InMemoryBackend with no external dependencies.
Integration tests require a live Postgres container and are marked
``pytest.mark.integration`` so ``pytest -m 'not integration'`` skips them.
"""

import contextlib
import time
from datetime import UTC, datetime, timedelta
from uuid import UUID

import pytest
from pydantic import BaseModel

from taskq import actor
from taskq._ids import new_uuid
from taskq.batch import EnqueueItem
from taskq.client._jobs import JobsClient
from taskq.exceptions import DuplicateIdempotencyKeyError, PayloadValidationError
from taskq.testing.clock import FakeClock
from taskq.testing.in_memory import InMemoryBackend

_START = datetime(2025, 1, 1, tzinfo=UTC)


# ── Test payloads and actors ───────────────────────────────────────────────


class _Payload(BaseModel):
    value: int = 0


@actor(name="batch_fast_test_actor")
async def _test_actor(_payload: _Payload) -> None:
    pass


@actor(
    name="batch_fast_unique_for_actor",
    unique_for=timedelta(minutes=15),
    unique_states=("pending", "scheduled", "running"),
)
async def _unique_for_actor(_payload: _Payload) -> None:  # pyright: ignore[reportUnusedFunction] # Why: actor decorator registers the function; it is accessed via the registry at test time.
    pass


def _make_backend() -> InMemoryBackend:
    return InMemoryBackend(clock=FakeClock(start=_START))


def _make_client(backend: InMemoryBackend) -> JobsClient:
    return JobsClient(backend=backend, clock=FakeClock(start=_START))


def _make_item(value: int = 0) -> EnqueueItem:
    return EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=value))


# ── Unit tests ─────────────────────────────────────────────────────────────


class TestTU1BasicBatchFastEnqueue:
    """enqueue_batch_fast returns correct count."""

    async def test_returns_count(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        count = await client.enqueue_batch_fast(items)

        assert isinstance(count, int)
        assert count == 3

    async def test_all_jobs_stored_in_backend(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(5)]

        count = await client.enqueue_batch_fast(items)

        assert count == 5
        assert len(backend._jobs) == 5  # type: ignore[reportPrivateUsage] # Why: test-only access


class TestTU2BatchIdInMetadata:
    """batch_id in metadata — all jobs have same metadata.batch_id."""

    async def test_all_jobs_have_same_batch_id(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        count = await client.enqueue_batch_fast(items)

        assert count == 3
        for _job_id, row in list(backend._jobs.items()):  # type: ignore[reportPrivateUsage] # Why: test-only
            assert "batch_id" in row.metadata

    async def test_caller_metadata_merged(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            metadata={"source": "api"},
        )

        count = await client.enqueue_batch_fast([item])

        assert count == 1
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.metadata.get("source") == "api"
            assert "batch_id" in row.metadata


class TestTU3AutoGeneratedBatchId:
    """Auto-generated batch_id — different for each call."""

    async def test_two_calls_get_different_batch_ids(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count1 = await client.enqueue_batch_fast([_make_item()])
        count2 = await client.enqueue_batch_fast([_make_item()])

        assert count1 == 1
        assert count2 == 1
        rows = list(backend._jobs.values())  # type: ignore[reportPrivateUsage]
        assert rows[0].metadata["batch_id"] != rows[1].metadata["batch_id"]


class TestTU4ExplicitBatchId:
    """Explicit batch_id — provided UUID used in all jobs."""

    async def test_explicit_batch_id_used(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        explicit_id = UUID("12345678-1234-5678-1234-567812345678")

        count = await client.enqueue_batch_fast([_make_item(), _make_item(1)], batch_id=explicit_id)

        assert count == 2
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.metadata.get("batch_id") == str(explicit_id)


class TestTU5EmptyListRaisesValueError:
    """Empty list raises ValueError."""

    async def test_empty_list_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        with pytest.raises(ValueError, match="empty"):
            await client.enqueue_batch_fast([])

    async def test_no_rows_inserted(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        with contextlib.suppress(ValueError):
            await client.enqueue_batch_fast([])

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]


class TestTU6TooManyItemsRaisesValueError:
    """50_001 items raises ValueError."""

    async def test_50001_items_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(50_001)]

        with pytest.raises(ValueError, match="50 000"):
            await client.enqueue_batch_fast(items)


class TestTU7Exactly50000ItemsSucceeds:
    """Exactly 50_000 items succeeds (in-memory)."""

    async def test_50000_items_succeeds(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(50_000)]

        count = await client.enqueue_batch_fast(items)

        assert count == 50_000


class TestTU8PayloadValidationFailure:
    """Payload validation failure — one bad item, entire batch rejected."""

    async def test_bad_payload_rejects_batch(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with pytest.raises(PayloadValidationError):
            await client.enqueue_batch_fast(items)

    async def test_no_rows_inserted_when_batch_fails(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with contextlib.suppress(PayloadValidationError):
            await client.enqueue_batch_fast(items)

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]


class TestTU9SingleItem:
    """Single item batch_fast."""

    async def test_single_item_returns_count_1(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count = await client.enqueue_batch_fast([_make_item(42)])

        assert count == 1
        row = next(iter(backend._jobs.values()))  # type: ignore[reportPrivateUsage]
        assert row.payload == {"value": 42}


class TestTU10StatusIsPending:
    """Jobs enqueued at current time have status 'pending'."""

    async def test_status_is_pending(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count = await client.enqueue_batch_fast([_make_item()])

        assert count == 1
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.status == "pending"


class TestTU11DuplicateKeyTypedError:
    """A duplicate idempotency key aborts the fast batch with the typed
    DuplicateIdempotencyKeyError — the same classification the PG COPY
    path gives (protocol parity; previously both surfaced a raw
    asyncpg.UniqueViolationError)."""

    async def test_intra_batch_duplicate_raises_typed_error(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        dup_key = f"dup-unit-{new_uuid()}"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=dup_key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=dup_key),
        ]

        with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
            await client.enqueue_batch_fast(items)

        assert exc_info.value.idempotency_key == dup_key
        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]  # Why: test-only admission check

    async def test_stored_pair_duplicate_raises_typed_error(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        key = f"stored-unit-{new_uuid()}"
        await client.enqueue_batch_fast(
            [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=key)]
        )

        with pytest.raises(DuplicateIdempotencyKeyError):
            await client.enqueue_batch_fast(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key)]
            )


class TestTUBatchTierUniqueForParity:
    """Actor-declared ``unique_for`` is not applied on the batch tiers —
    on EITHER backend.

    The PG batch tiers (the unnest INSERT and the COPY) never run the
    unique_for preflight: a bulk statement cannot take a per-identity
    advisory lock without the per-item round trips that defeat bulk
    throughput, so every batch item writes and unique_for items are
    conservatively fully counted toward ``max_pending`` instead (the
    single path is where the preflight pays — see
    ``test_unique_for_caller_conn_serialization.py`` and
    ``test_postgres_unique_for_single_flight.py``). The in-memory batch
    tier must match that behavior, not improve on it: a test suite run
    against ``InMemoryBackend`` that saw batch-path unique_for dedup
    would certify dedup production never performs — false confidence,
    the worst kind this project ships.

    Whether the batch tier SHOULD honor ``unique_for`` is an open owner
    decision (River enforces batch uniqueness with a partial unique
    index + ON CONFLICT —
    vendor/river/riverdriver/riverpgxv5/internal/dbsqlc/river_job.sql);
    these pins hold the parity with current production behavior, not an
    endorsement of it.
    """

    def _unique_for_items(self, values: tuple[int, ...], identity: str) -> list[EnqueueItem]:
        return [
            EnqueueItem(
                actor_ref=_unique_for_actor, payload=_Payload(value=v), identity_key=identity
            )
            for v in values
        ]

    async def test_same_identity_items_in_one_batch_both_insert(self) -> None:
        """Two items with the same (actor, identity_key) in ONE batch
        call both insert — the PG unnest INSERT has no per-item
        unique_for logic, so it writes both."""
        backend = _make_backend()
        client = _make_client(backend)

        handle = await client.enqueue_batch(self._unique_for_items((1, 2), "acct:parity"))

        ids = [h.job_id for h in handle.job_handles]
        assert len(ids) == 2, f"both batch items must produce jobs; got {ids}"
        assert len(set(ids)) == 2, (
            f"a batch-path unique_for dedup produced one job for two items; "
            f"PG writes both — ids={ids}"
        )
        assert len(backend._jobs) == 2  # type: ignore[reportPrivateUsage]  # Why: admission check against the mirror's store

    async def test_same_identity_items_across_two_batches_both_insert(self) -> None:
        """The same divergence across two batch CALLS: PG's second bulk
        INSERT never consults unique_for, so it writes alongside the
        first call's row."""
        backend = _make_backend()
        client = _make_client(backend)

        await client.enqueue_batch(self._unique_for_items((1,), "acct:parity-2"))
        await client.enqueue_batch(self._unique_for_items((2,), "acct:parity-2"))

        assert len(backend._jobs) == 2, (
            "the second batch deduped against the first batch's row; the PG "
            "batch tier never runs the unique_for preflight"
        )

    async def test_same_identity_items_via_batch_fast_both_insert(self) -> None:
        """The COPY tier: unique_for items are fully written (and fully
        counted toward max_pending) — no preflight, no dedup. The STORE
        is the observable that separates this from a dedup: the mirror's
        fast tier counts dedup returns in its row count, so ``count``
        alone cannot distinguish "2 written" from "1 written + 1
        deduped"."""
        backend = _make_backend()
        client = _make_client(backend)

        count = await client.enqueue_batch_fast(self._unique_for_items((1, 2), "acct:parity-3"))

        assert count == 2, (
            f"the fast tier wrote {count} of 2 same-identity unique_for items; "
            f"the PG COPY path writes every row"
        )
        assert len(backend._jobs) == 2, (  # type: ignore[reportPrivateUsage]  # Why: admission check against the mirror's store
            "the fast tier deduped a unique_for item in memory; the PG COPY "
            "path never runs the unique_for preflight"
        )

    async def test_single_enqueue_unique_for_still_dedups(self) -> None:
        """The no-overreach guard: stripping unique_for is a BATCH-tier
        parity decision. The single-enqueue path keeps the single-flight
        contract (PIN 5 semantics,
        ``test_pinned_invariants.py::test_unique_for_does_not_dedupe_onto_a_succeeded_job``
        and the in-memory pins in ``test_dedup_logging.py``)."""
        backend = _make_backend()
        client = _make_client(backend)

        first = await client.enqueue(
            _unique_for_actor, _Payload(value=1), identity_key="acct:parity-4"
        )
        second = await client.enqueue(
            _unique_for_actor, _Payload(value=2), identity_key="acct:parity-4"
        )

        assert second.job_id == first.job_id, (
            "the single-enqueue path stopped deduping a still-pending "
            "identity — the single-flight guard itself is broken"
        )
        assert second.was_existing is True
        assert len(backend._jobs) == 1  # type: ignore[reportPrivateUsage]  # Why: admission check against the mirror's store


# ── Integration tests ─────────────────────────────────────────────────────


@pytest.mark.integration
class TestTI1BasicPG:
    """basic COPY FROM insert against real PG."""

    async def test_100_items_count_correct(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti1"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        items = [_make_item(i) for i in range(100)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 100

        conn = await asyncpg.connect(pg_dsn)
        try:
            row_count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert row_count == 100
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI2BatchIdInAllRows:
    """All inserted rows carry the same batch_id."""

    async def test_500_items_same_batch_id(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti2"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        items = [_make_item(i) for i in range(500)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 500

        conn = await asyncpg.connect(pg_dsn)
        try:
            rows = await conn.fetch(
                f'SELECT id, metadata FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert len(rows) == 500
            for rec in rows:
                md = rec["metadata"]
                if isinstance(md, str):
                    from taskq._json import loads

                    md = loads(md)
                assert str(md.get("batch_id")) == str(batch_id)
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI3SingleItem:
    """single item COPY FROM against real PG."""

    async def test_single_item(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti3"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=99))],
                batch_id=batch_id,
            )

        assert count == 1

        conn = await asyncpg.connect(pg_dsn)
        try:
            rec = await conn.fetchrow(
                f'SELECT * FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert rec is not None
            assert rec["status"] in ("pending", "")
            assert rec["payload"] is not None
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI4LargeBatch10K:
    """10K item batch via COPY FROM."""

    async def test_10k_items(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti4"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        items = [_make_item(i % 1000) for i in range(10_000)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 10_000

        conn = await asyncpg.connect(pg_dsn)
        try:
            row_count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert row_count == 10_000
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI5PerformanceComparison:
    """COPY FROM faster than UNNEST for 1K items."""

    @pytest.mark.slow  # perf comparison, not correctness; relaxed multiplier under load
    async def test_copy_faster_than_unnest_1k(self, pg_dsn: str) -> None:
        """For 1K items (max for enqueue_batch), COPY FROM must be faster than UNNEST."""
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti5"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items_1k = [_make_item(i % 1000) for i in range(1_000)]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Time COPY FROM
            batch_id_fast = new_uuid()
            start = time.monotonic()
            count_fast = await tq.enqueue_batch_fast(items_1k, batch_id=batch_id_fast)
            elapsed_fast = time.monotonic() - start
            assert count_fast == 1_000

            # Clean up inserted rows
            conn = await asyncpg.connect(pg_dsn)
            try:
                await conn.execute(
                    f'DELETE FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                    dumps_str({"batch_id": str(batch_id_fast)}),
                )
            finally:
                await conn.close()

            # Time UNNEST (regular enqueue_batch)
            batch_id_unnest = new_uuid()
            start = time.monotonic()
            handle = await tq.enqueue_batch(items_1k, batch_id=batch_id_unnest)
            elapsed_unnest = time.monotonic() - start
            assert handle.size == 1_000

        assert elapsed_fast <= elapsed_unnest * 20, (
            f"COPY FROM ({elapsed_fast:.3f}s) should be competitive with "
            f"UNNEST ({elapsed_unnest:.3f}s) for 1K items"
        )


@pytest.mark.integration
class TestTI6PerformanceComparison4000:
    """COPY FROM faster than UNNEST for 1K items (second run)."""

    @pytest.mark.slow  # perf comparison, not correctness; relaxed multiplier under load
    async def test_copy_faster_than_unnest_1k_second(self, pg_dsn: str) -> None:
        """For 1K items, COPY FROM must be faster than UNNEST (repeatability)."""
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti6"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items_1k = [_make_item(i % 1000) for i in range(1_000)]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Time COPY FROM
            batch_id_fast = new_uuid()
            start = time.monotonic()
            count_fast = await tq.enqueue_batch_fast(items_1k, batch_id=batch_id_fast)
            elapsed_fast = time.monotonic() - start
            assert count_fast == 1_000

            # Clean up
            conn = await asyncpg.connect(pg_dsn)
            try:
                await conn.execute(
                    f'DELETE FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                    dumps_str({"batch_id": str(batch_id_fast)}),
                )
            finally:
                await conn.close()

            # Time UNNEST
            batch_id_unnest = new_uuid()
            start = time.monotonic()
            handle = await tq.enqueue_batch(items_1k, batch_id=batch_id_unnest)
            elapsed_unnest = time.monotonic() - start
            assert handle.size == 1_000

        assert elapsed_fast <= elapsed_unnest * 20, (
            f"COPY FROM ({elapsed_fast:.3f}s) should be competitive with "
            f"UNNEST ({elapsed_unnest:.3f}s) for 1K items"
        )


@pytest.mark.integration
class TestTI7TransactionalBatchFast:
    """Transactional batch_fast — rollback means no rows."""

    async def test_rollback_means_no_rows(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti7"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            tx_conn = await asyncpg.connect(pg_dsn)
            tr = tx_conn.transaction()
            await tr.start()
            try:
                await tq.enqueue_batch_fast(
                    [_make_item(i) for i in range(3)],
                    batch_id=batch_id,
                    connection=tx_conn,
                )
            finally:
                await tr.rollback()
                await tx_conn.close()

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI8DuplicateIdempotencyKeyFails:
    """Duplicate idempotency_key aborts the entire COPY batch with the
    typed DuplicateIdempotencyKeyError (classification only — the
    all-or-nothing abort is deliberate; nothing is written)."""

    async def test_duplicate_key_fails_entire_batch(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti8"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = new_uuid()
        dup_key = f"dup-key-{new_uuid()}"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=dup_key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=dup_key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=3)),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
                await tq.enqueue_batch_fast(items, batch_id=batch_id)
        assert not isinstance(exc_info.value, asyncpg.UniqueViolationError)
        assert exc_info.value.idempotency_key == dup_key

        # Verify no rows inserted
        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()

    async def test_key_raced_against_stored_pair_raises_typed_error(self, pg_dsn: str) -> None:
        """The raced variant: the pair was already committed by an earlier
        (non-fast) batch, and the COPY violates the composite arbiter
        against the stored row — same typed classification, whole COPY
        aborted, nothing from this batch written."""
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti8b"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        key = f"raced-key-{new_uuid()}"
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Commit the pair through the dedup-capable path first.
            await tq.enqueue_batch(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=0), idempotency_key=key)]
            )
            with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
                await tq.enqueue_batch_fast(
                    [
                        EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1)),
                        EnqueueItem(
                            actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key
                        ),
                    ]
                )
        assert not isinstance(exc_info.value, asyncpg.UniqueViolationError)

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            # Only the pre-stored row: the COPY aborted before writing.
            assert count == 1
        finally:
            await conn.close()


@pytest.mark.integration
class TestTIScopeRoundTripThroughCopy:
    """idempotency_scope and idempotency_key must land in the right columns
    through the positional COPY record tuple. The tuple is built by hand in
    _enqueue_batch_fast and aligned to COPY_FROM_COLUMNS by position only --
    a misalignment here inserts successfully but writes values into the
    wrong columns, exactly the bug class the archive-sweep fix addresses.
    """

    async def test_scope_and_key_land_in_correct_columns(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_scope_rt"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        key = f"copy-key-{new_uuid()}"
        items = [
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=1),
                idempotency_key=key,
                idempotency_scope="run-A",
            ),
            # Same key in a different scope: accepted by the composite index.
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=2),
                idempotency_key=key,
                idempotency_scope="run-B",
            ),
            # Default/global scope.
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=3),
                idempotency_key=f"{key}-other",
            ),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items)

        assert count == 3

        conn = await asyncpg.connect(pg_dsn)
        try:
            rows = await conn.fetch(
                f'SELECT payload, idempotency_scope, idempotency_key FROM "{schema}".jobs'  # noqa: S608
            )
            by_scope = {r["idempotency_scope"]: r for r in rows}
            assert by_scope["run-A"]["idempotency_key"] == key
            assert by_scope["run-B"]["idempotency_key"] == key
            assert by_scope[""]["idempotency_key"] == f"{key}-other"
            # And not bled into neighboring text columns.
            assert all(r["idempotency_scope"] in ("run-A", "run-B", "") for r in rows)
        finally:
            await conn.close()

    async def test_same_scope_duplicate_key_aborts_batch(self, pg_dsn: str) -> None:
        """The composite-index analogue of TestTI8: same key AND same
        explicit scope within one COPY batch violates
        jobs_idempotency_scope_key_uniq and aborts the whole batch with
        the typed classification."""
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_scope_dup"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        key = f"copy-dup-{new_uuid()}"
        items = [
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=1),
                idempotency_key=key,
                idempotency_scope="run-A",
            ),
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=2),
                idempotency_key=key,
                idempotency_scope="run-A",
            ),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
                await tq.enqueue_batch_fast(items)
        assert not isinstance(exc_info.value, asyncpg.UniqueViolationError)
        assert exc_info.value.idempotency_scope == "run-A"

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI9PayloadValidationFailureIntegration:
    """Payload validation failure — entire batch rejected, no partial insert."""

    async def test_no_partial_insert(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti9"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        class _BadPayload(BaseModel):
            name: str = "bad"

        items = [_make_item(i) for i in range(5)]
        items.append(EnqueueItem(actor_ref=_test_actor, payload=_BadPayload()))

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(PayloadValidationError):
                await tq.enqueue_batch_fast(items)

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTIScopeAttributionVerification:
    """The COPY duplicate classification's attribution is verified against
    the batch's own (scope, key) candidates before it is trusted.

    Postgres renders the composite-index violation detail with RAW,
    unquoted values — a scope containing ``, `` makes the detail ambiguous
    under positional parsing: scope ``run,A`` key ``k`` reports
    ``Key (idempotency_scope, idempotency_key)=(run,A, k) already exists.``,
    which a left-to-right split mis-reads as scope ``run`` key ``A, k``.
    The attribution therefore MATCHES the rendered detail against each
    candidate pair instead of parsing it: the unique candidate whose
    rendered detail equals the server's detail is attributed exactly, and
    genuinely ambiguous renderings (two distinct candidate pairs producing
    the same detail text) degrade to unattributed-but-typed — never a
    wrong pair (the in-memory mirror attributes exactly by construction;
    PG parity is best-effort with a verified fallback)."""

    async def test_comma_space_scope_duplicate_attributed_exactly(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_scope_attr"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        key = f"comma-scope-{new_uuid()}"
        items = [
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=1),
                idempotency_key=key,
                idempotency_scope="run,A",
            ),
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=2),
                idempotency_key=key,
                idempotency_scope="run,A",
            ),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
                await tq.enqueue_batch_fast(items)
        assert not isinstance(exc_info.value, asyncpg.UniqueViolationError)
        # Verified attribution, not a positional mis-parse: the pair named
        # is the batch's own ("run,A", key), not ("run", "A, <key>").
        assert exc_info.value.idempotency_scope == "run,A"
        assert exc_info.value.idempotency_key == key

    async def test_ambiguous_comma_space_pairs_degrade_to_unattributed(self, pg_dsn: str) -> None:
        """Two DISTINCT candidate pairs render to the same detail text —
        ``(a, b, c)`` is both ``("a, b", "c")`` and ``("a", "b, c")`` — so
        the detail cannot name one pair honestly: the attribution fields
        degrade to None (typed error, no attribution) instead of guessing."""
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_scope_ambig"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items = [
            # The in-batch duplicate — the actual violator.
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=1),
                idempotency_key="c",
                idempotency_scope="a, b",
            ),
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=2),
                idempotency_key="c",
                idempotency_scope="a, b",
            ),
            # A DISTINCT pair rendering to the same detail text: the
            # ambiguity foil. Inserted once — no violation of its own.
            EnqueueItem(
                actor_ref=_test_actor,
                payload=_Payload(value=3),
                idempotency_key="b, c",
                idempotency_scope="a",
            ),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(DuplicateIdempotencyKeyError) as exc_info:
                await tq.enqueue_batch_fast(items)
        assert not isinstance(exc_info.value, asyncpg.UniqueViolationError)
        # Ambiguous rendering: neither pair is named — never a guess.
        assert exc_info.value.idempotency_scope is None
        assert exc_info.value.idempotency_key is None

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTIPastScheduledAtNormalized:
    """An explicit past scheduled_at is the caller's absolute intent.

    Every enqueue arm (single, batch, COPY) stores a non-None scheduled_at
    verbatim and lets the server CASE decide the status — a past value
    lands ``pending`` and is immediately dispatchable.  "Immediate" is
    expressed as ``scheduled_at=None`` (the server stamps it); the COPY arm
    used to normalize past values to the Python batch clock, a cross-domain
    decision the post-COPY fixup UPDATE removed.
    """

    async def test_past_scheduled_at_not_stored_stale(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_past_scheduled"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        # A scheduled_at well in the past relative to the live PG clock.
        past = _START
        batch_id = new_uuid()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), scheduled_at=past)],
                batch_id=batch_id,
            )

        assert count == 1

        conn = await asyncpg.connect(pg_dsn)
        try:
            rec = await conn.fetchrow(
                f'SELECT status, scheduled_at FROM "{schema}".jobs '  # noqa: S608
                f"WHERE metadata @> $1::jsonb",
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert rec is not None
            # Past ⇒ pending (immediately dispatchable), and the caller's
            # explicit absolute is preserved verbatim — byte-for-byte the
            # INSERT arms' semantics.
            assert rec["status"] == "pending"
            assert rec["scheduled_at"] == past
        finally:
            await conn.close()
