"""Hypothesis property test for ConcurrencyReservation invariant.

For N slots, at most N slots are held simultaneously across any
acquire/release sequence generated by Hypothesis. After every operation
the held-count invariant is checked:

    ``COUNT(*) WHERE job_id IS NOT NULL <= N``

Uses the in-memory ``_InMemorySlotTable`` with ``FakeClock`` so the test
is deterministic and fast — no real PG required.
"""

from datetime import UTC, datetime, timedelta

from hypothesis import given, settings
from hypothesis import strategies as st

from taskq._ids import new_uuid
from taskq.exceptions import ReservationUnavailable
from taskq.ratelimit.reservation import _InMemorySlotTable
from taskq.testing.clock import FakeClock

_START = datetime(2025, 1, 1, tzinfo=UTC)
_LEASE = timedelta(seconds=10)
_N_SLOTS = 4

_OPERATION_STRATEGY = st.lists(
    st.tuples(
        st.sampled_from(["acquire", "release"]),
        st.integers(min_value=0, max_value=100),
        st.floats(min_value=0.0, max_value=20.0, allow_nan=False, allow_infinity=False),
    ),
    max_size=300,
)


def _count_held(table: _InMemorySlotTable, bucket_name: str) -> int:
    count = 0
    for idx in table.get_slot_indices(bucket_name):
        slot = table.get_slot(bucket_name, idx)
        if slot is not None and slot.job_id is not None:
            count += 1
    return count


@given(operations=_OPERATION_STRATEGY)
@settings(max_examples=300, deadline=None)
async def test_reservation_invariant(
    operations: list[tuple[str, int, float]],
) -> None:
    """Reservation invariant — for N slots, at most N slots held
    simultaneously across any acquire/release sequence."""
    clock = FakeClock(_START)
    table = _InMemorySlotTable(clock)
    bucket_name = "prop_bucket"
    table.ensure_slots(bucket_name, _N_SLOTS)

    held_slots: dict[int, tuple[tuple[object, ...], object]] = {}

    for op_type, seed, advance_s in operations:
        clock.advance(timedelta(seconds=advance_s))

        if op_type == "acquire":
            job_id = new_uuid()
            worker_id = new_uuid()
            try:
                idx = table.acquire(bucket_name, job_id, worker_id, _LEASE)
                held_slots[idx] = ((job_id, worker_id), clock.now() + _LEASE)
            except ReservationUnavailable:
                pass
        elif op_type == "release":
            if held_slots:
                release_key = seed % len(held_slots)
                slot_idx = sorted(held_slots.keys())[release_key]
                _job_ids, worker_id = held_slots[slot_idx]
                table.release(bucket_name, slot_idx, worker_id)  # type: ignore[arg-type] # Why: worker_id is UUID from new_uuid(); stored as object in held_slots tuple for generality
                del held_slots[slot_idx]

        held_count = _count_held(table, bucket_name)
        assert held_count <= _N_SLOTS, (
            f"over-allocation: {held_count} slots held > {_N_SLOTS} after {op_type}"
        )
