"""Tests for the enqueue_batch primitive.

Unit tests run against InMemoryBackend with no external dependencies.
Integration tests require a live Postgres container and are marked
``pytest.mark.integration`` so ``pytest -m 'not integration'`` skips them.
"""

import contextlib
import time
from datetime import UTC, datetime
from typing import Any
from unittest.mock import patch
from uuid import UUID, uuid4

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from pydantic import BaseModel

from taskq import actor
from taskq.batch import BatchCompletionStatus, BatchHandle, EnqueueItem
from taskq.client._handle import JobHandle
from taskq.client._jobs import JobsClient
from taskq.exceptions import MaxPendingExceededError, PayloadValidationError
from taskq.testing.clock import FakeClock
from taskq.testing.in_memory import InMemoryBackend

_START = datetime(2025, 1, 1, tzinfo=UTC)


# ── Test payloads and actors ───────────────────────────────────────────────


class _Payload(BaseModel):
    value: int = 0


@actor(name="batch_test_actor")
async def _test_actor(_payload: _Payload) -> None:
    pass


def _make_backend() -> InMemoryBackend:
    return InMemoryBackend(clock=FakeClock(start=_START))


def _make_client(backend: InMemoryBackend) -> JobsClient:
    return JobsClient(backend=backend, clock=FakeClock(start=_START))


def _make_item(value: int = 0) -> EnqueueItem:
    return EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=value))


# ── Unit tests ─────────────────────────────────────────────────────────────


class TestTU1BasicBatchEnqueue:
    """Basic batch enqueue — 3 items, returns BatchHandle with 3 handles."""

    async def test_returns_batch_handle(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        handle = await client.enqueue_batch(items)

        assert isinstance(handle, BatchHandle)
        assert handle.size == 3
        assert len(handle.job_handles) == 3
        assert isinstance(handle.batch_id, UUID)

    async def test_all_handles_are_job_handles(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        handle = await client.enqueue_batch(items)

        for h in handle.job_handles:
            assert isinstance(h, JobHandle)

    async def test_all_jobs_stored_in_backend(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        handle = await client.enqueue_batch(items)

        for h in handle.job_handles:
            row = await backend.get(h.job_id)
            assert row is not None


class TestTU2BatchIdInMetadata:
    """batch_id in metadata — all 3 jobs have same metadata.batch_id."""

    async def test_all_jobs_have_same_batch_id(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        handle = await client.enqueue_batch(items)

        batch_id_str = str(handle.batch_id)
        for h in handle.job_handles:
            row = await backend.get(h.job_id)
            assert row is not None
            assert row.metadata.get("batch_id") == batch_id_str

    async def test_batch_id_in_metadata_is_string(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        handle = await client.enqueue_batch([_make_item()])

        row = await backend.get(handle.job_handles[0].job_id)
        assert row is not None
        assert isinstance(row.metadata.get("batch_id"), str)


class TestTU3AutoGeneratedBatchId:
    """Auto-generated batch_id — UUIDv7 generated when not provided."""

    async def test_auto_batch_id_is_uuid(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        handle = await client.enqueue_batch([_make_item()])

        assert isinstance(handle.batch_id, UUID)

    async def test_two_calls_get_different_batch_ids(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        handle1 = await client.enqueue_batch([_make_item()])
        handle2 = await client.enqueue_batch([_make_item()])

        assert handle1.batch_id != handle2.batch_id


class TestTU4ExplicitBatchId:
    """Explicit batch_id — provided UUID used in all jobs."""

    async def test_explicit_batch_id_used(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        explicit_id = UUID("12345678-1234-5678-1234-567812345678")

        handle = await client.enqueue_batch([_make_item(), _make_item(1)], batch_id=explicit_id)

        assert handle.batch_id == explicit_id

    async def test_explicit_batch_id_in_all_metadata(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        explicit_id = UUID("12345678-1234-5678-1234-567812345678")

        handle = await client.enqueue_batch([_make_item(i) for i in range(3)], batch_id=explicit_id)

        for h in handle.job_handles:
            row = await backend.get(h.job_id)
            assert row is not None
            assert row.metadata.get("batch_id") == str(explicit_id)


class TestTU5EmptyListRaisesValueError:
    """Empty list raises ValueError."""

    async def test_empty_list_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        with pytest.raises(ValueError, match="empty"):
            await client.enqueue_batch([])


class TestTU6TooManyItemsRaisesValueError:
    """1001 items raises ValueError."""

    async def test_1001_items_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(1001)]

        with pytest.raises(ValueError, match="1000"):
            await client.enqueue_batch(items)


class TestTU7Exactly1000ItemsSucceeds:
    """Exactly 1000 items succeeds."""

    async def test_1000_items_succeeds(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(1000)]

        handle = await client.enqueue_batch(items)

        assert handle.size == 1000
        assert len(handle.job_handles) == 1000


class TestTU8PayloadValidationFailure:
    """Payload validation failure — one bad item, entire batch rejected."""

    async def test_bad_payload_rejects_batch(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        # _Payload expects value: int; pass a string that cannot coerce
        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with pytest.raises(PayloadValidationError):
            await client.enqueue_batch(items)

    async def test_no_rows_inserted_when_batch_fails(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with contextlib.suppress(PayloadValidationError):
            await client.enqueue_batch(items)

        # No jobs should be stored
        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]  # Why: test-only access to verify zero rows inserted


class TestTU9PerItemMetadataMerged:
    """Per-item metadata merged with batch_id."""

    async def test_item_metadata_and_batch_id_both_present(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            metadata={"source": "api"},
        )
        handle = await client.enqueue_batch([item])

        row = await backend.get(handle.job_handles[0].job_id)
        assert row is not None
        assert row.metadata.get("source") == "api"
        assert "batch_id" in row.metadata

    async def test_batch_id_is_string_type(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            metadata={"source": "api", "priority": 42},
        )
        handle = await client.enqueue_batch([item])

        row = await backend.get(handle.job_handles[0].job_id)
        assert row is not None
        assert isinstance(row.metadata.get("batch_id"), str)
        assert row.metadata.get("source") == "api"
        assert row.metadata.get("priority") == 42


# ── BatchCompletionStatus unit test ──────────────────────────────


class TestTU10BatchCompletionStatus:
    """BatchCompletionStatus construction and field correctness.

    A real ``BatchHandle.status(db)`` call requires an asyncpg connection,
    which is unavailable at the unit tier. This test validates the model
    directly; a separate integration test exercises the real async path.
    """

    def test_construction_and_field_values(self) -> None:
        status = BatchCompletionStatus(
            total=10,
            pending=3,
            succeeded=4,
            failed=2,
            cancelled=1,
            crashed=0,
            abandoned=0,
        )
        assert status.total == 10
        assert status.pending == 3
        assert status.succeeded == 4
        assert status.failed == 2
        assert status.cancelled == 1
        assert status.crashed == 0
        assert status.abandoned == 0

    def test_is_complete_false_with_pending(self) -> None:
        status = BatchCompletionStatus(
            total=5, pending=1, succeeded=4, failed=0, cancelled=0, crashed=0, abandoned=0
        )
        assert status.is_complete is False

    def test_is_complete_true_when_all_terminal(self) -> None:
        status = BatchCompletionStatus(
            total=5, pending=0, succeeded=3, failed=1, cancelled=1, crashed=0, abandoned=0
        )
        assert status.is_complete is True


class TestTU11IsCompleteProperty:
    """is_complete property — True when pending==0."""

    def test_is_complete_true_when_no_pending(self) -> None:
        status = BatchCompletionStatus(
            total=3,
            pending=0,
            succeeded=2,
            failed=1,
            cancelled=0,
            crashed=0,
            abandoned=0,
        )
        assert status.is_complete is True

    def test_is_complete_false_when_pending_nonzero(self) -> None:
        status = BatchCompletionStatus(
            total=3,
            pending=1,
            succeeded=2,
            failed=0,
            cancelled=0,
            crashed=0,
            abandoned=0,
        )
        assert status.is_complete is False

    def test_is_complete_false_when_all_pending(self) -> None:
        status = BatchCompletionStatus(
            total=3,
            pending=3,
            succeeded=0,
            failed=0,
            cancelled=0,
            crashed=0,
            abandoned=0,
        )
        assert status.is_complete is False

    def test_is_complete_true_when_all_succeeded(self) -> None:
        status = BatchCompletionStatus(
            total=5,
            pending=0,
            succeeded=5,
            failed=0,
            cancelled=0,
            crashed=0,
            abandoned=0,
        )
        assert status.is_complete is True


# ── Integration tests ─────────────────────────────────────────────────────


@pytest.mark.integration
class TestTI1FivehundredItemBatch:
    """500-item batch, verify 500 rows with same batch_id."""

    async def test_500_item_batch(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti1"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            items = [_make_item(i) for i in range(500)]
            handle = await tq.enqueue_batch(items)

        assert handle.size == 500
        assert len(handle.job_handles) == 500

        # Verify all rows stored with the same batch_id
        conn = await asyncpg.connect(pg_dsn)
        try:
            from taskq._json import dumps_str

            batch_id_str = str(handle.batch_id)
            rows = await conn.fetch(
                f'SELECT id FROM "{schema}".jobs WHERE metadata @> $1::jsonb',
                dumps_str({"batch_id": batch_id_str}),
            )
            assert len(rows) == 500
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI2GINIndexUsed:
    """GIN index used by metadata @> query — two batches, query X returns only X."""

    async def test_batch_x_returns_exactly_5(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti2"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Enqueue batch X (5 items)
            items_x = [_make_item(i) for i in range(5)]
            handle_x = await tq.enqueue_batch(items_x)

            # Enqueue batch Y (3 items)
            items_y = [_make_item(i) for i in range(3)]
            await tq.enqueue_batch(items_y)

        # Query batch X specifically
        conn = await asyncpg.connect(pg_dsn)
        try:
            from taskq._json import dumps_str

            rows = await conn.fetch(
                f'SELECT id FROM "{schema}".jobs WHERE metadata @> $1::jsonb',
                dumps_str({"batch_id": str(handle_x.batch_id)}),
            )
            assert len(rows) == 5
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI3TransactionalBatch:
    """Transactional batch with connection parameter — rollback = no rows."""

    async def test_rollback_means_no_rows(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti3"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Open a connection manually and use a transaction we roll back
            tx_conn = await asyncpg.connect(pg_dsn)
            tr = tx_conn.transaction()
            await tr.start()
            try:
                await tq.enqueue_batch(
                    [_make_item(i) for i in range(3)],
                    connection=tx_conn,
                )
            finally:
                await tr.rollback()
                await tx_conn.close()

        # Verify no rows were persisted
        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')
            assert count == 0
        finally:
            await conn.close()


# ── BatchCompletionStatus against real PG ────────────────────────


@pytest.mark.integration
class TestTI4BatchCompletionStatusRealPG:
    """BatchCompletionStatus against real PG."""

    async def test_status_after_all_succeeded(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti4"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            items = [_make_item(i) for i in range(50)]
            handle = await tq.enqueue_batch(items)

        # Mark all 50 jobs as succeeded via raw SQL
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(
                f"UPDATE \"{schema}\".jobs SET status = 'succeeded' WHERE metadata @> $1::jsonb",
                dumps_str({"batch_id": str(handle.batch_id)}),
            )
            status = await handle.status(conn, schema=schema)
        finally:
            await conn.close()

        assert status.succeeded == 50
        assert status.pending == 0
        assert status.total == 50
        assert status.is_complete is True
        assert status.failed == 0
        assert status.cancelled == 0
        assert status.crashed == 0
        assert status.abandoned == 0


# ── Per-item idempotency_key collision integration ──────────────


@pytest.mark.integration
class TestTI5IdempotencyKeyCollisionIntegration:
    """Per-item idempotency_key collision integration test."""

    async def test_two_items_same_idempotency_key(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti5"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        key = f"idem-collision-{uuid4()}"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            handle = await tq.enqueue_batch(items)

        assert len(handle.job_handles) == 2
        assert handle.job_handles[0].job_id == handle.job_handles[1].job_id
        assert handle.job_handles[1].was_existing is True

        conn = await asyncpg.connect(pg_dsn)
        try:
            rows = await conn.fetch(
                f'SELECT id FROM "{schema}".jobs WHERE idempotency_key = $1',
                key,
            )
        finally:
            await conn.close()

        assert len(rows) == 1


# ── Single INSERT statement verified ────────────────────────────


@pytest.mark.integration
class TestTI6SingleInsertStatement:
    """Single INSERT statement verified — exactly one fetch call during INSERT."""

    async def test_single_fetch_call_for_insert(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti6"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items = [_make_item(i) for i in range(500)]
        insert_call_count = 0
        original_fetch = asyncpg.Connection.fetch

        async def _counting_fetch(
            conn_self: asyncpg.Connection, query: str, *args: object
        ) -> list[asyncpg.Record]:
            nonlocal insert_call_count
            result = await original_fetch(conn_self, query, *args)
            if "INSERT" in query.upper().split()[0]:
                insert_call_count += 1
            return result  # type: ignore[return-value]  # Why: asyncpg Record list returned from real fetch; wrapper delegates faithfully

        with patch.object(asyncpg.Connection, "fetch", _counting_fetch):
            async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
                handle = await tq.enqueue_batch(items)

        assert insert_call_count == 1
        assert handle.size == 500


# ── GIN index used by metadata @> $1::jsonb ───────────────────


def _find_index_in_plan(plan: dict[str, object], index_name: str) -> bool:
    """Recursively search EXPLAIN plan for an index scan on *index_name*."""
    node_type = plan.get("Node Type", "")
    index_name_val = plan.get("Index Name", "")
    if "Index Scan" in str(node_type) and index_name in str(index_name_val):
        return True
    for key in ("Plans", "Plan"):
        child = plan.get(key)
        if isinstance(child, list):
            for sub in child:
                if isinstance(sub, dict) and _find_index_in_plan(sub, index_name):
                    return True
        elif isinstance(child, dict) and _find_index_in_plan(child, index_name):
            return True
    return False


def _extract_execution_time_ms(plan: dict[str, object]) -> float:
    """Extract 'Actual Total Time' from EXPLAIN ANALYZE output."""
    val = plan.get("Actual Total Time")
    if isinstance(val, (int, float)):
        return float(val)
    for key in ("Plans", "Plan"):
        child = plan.get(key)
        if isinstance(child, list):
            for sub in child:
                if isinstance(sub, dict):
                    t = _extract_execution_time_ms(sub)
                    if t > 0:
                        return t
        elif isinstance(child, dict):
            t = _extract_execution_time_ms(child)
            if t > 0:
                return t
    return 0.0


@pytest.mark.integration
class TestTIGinIndexUsed:
    """GIN index used by ``metadata @> $1::jsonb``."""

    async def test_gin_index_scan_on_containment_query(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tigin"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        # Seed 10 000 jobs across 5 batch IDs via copy_records_to_table
        conn = await asyncpg.connect(pg_dsn)
        try:
            batch_ids = [str(uuid4()) for _ in range(5)]
            records: list[tuple[object, ...]] = []
            for i in range(10_000):
                batch_id = batch_ids[i % 5]
                records.append(
                    (
                        uuid4(),
                        "seed_actor",
                        "default",
                        "{}",
                        "pending",
                        3,
                        "transient",
                        dumps_str({"batch_id": batch_id}),
                    )
                )
            await conn.copy_records_to_table(
                "jobs",
                schema_name=schema,
                records=records,
                columns=[
                    "id",
                    "actor",
                    "queue",
                    "payload",
                    "status",
                    "max_attempts",
                    "retry_kind",
                    "metadata",
                ],
            )
        finally:
            await conn.close()

        target_batch = batch_ids[0]
        conn = await asyncpg.connect(pg_dsn)
        try:
            explain_rows = await conn.fetch(
                f"EXPLAIN (ANALYZE, FORMAT JSON) "
                f'SELECT * FROM "{schema}".jobs WHERE metadata @> $1::jsonb',
                dumps_str({"batch_id": target_batch}),
            )
        finally:
            await conn.close()

        from taskq._json import loads as _json_loads

        plan_data = _json_loads(explain_rows[0]["QUERY PLAN"])[0]["Plan"]
        assert _find_index_in_plan(plan_data, "jobs_metadata_gin_idx")
        exec_time = _extract_execution_time_ms(plan_data)
        assert exec_time < 200, f"GIN query took {exec_time}ms, expected < 200ms"


# ── Sequential scan for wrong ->> form ────────────────────


@pytest.mark.integration
class TestTIGinNegSequentialScanForTextExtraction:
    """Sequential scan confirmed for ``metadata->>'batch_id' = $1``."""

    async def test_text_extraction_uses_seq_scan(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tigin_neg"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        # Seed 10 000 jobs across 5 batch IDs via copy_records_to_table
        conn = await asyncpg.connect(pg_dsn)
        try:
            batch_ids = [str(uuid4()) for _ in range(5)]
            records: list[tuple[object, ...]] = []
            for i in range(10_000):
                batch_id = batch_ids[i % 5]
                records.append(
                    (
                        uuid4(),
                        "seed_actor",
                        "default",
                        "{}",
                        "pending",
                        3,
                        "transient",
                        dumps_str({"batch_id": batch_id}),
                    )
                )
            await conn.copy_records_to_table(
                "jobs",
                schema_name=schema,
                records=records,
                columns=[
                    "id",
                    "actor",
                    "queue",
                    "payload",
                    "status",
                    "max_attempts",
                    "retry_kind",
                    "metadata",
                ],
            )
        finally:
            await conn.close()

        target_batch = batch_ids[0]
        conn = await asyncpg.connect(pg_dsn)
        try:
            explain_rows = await conn.fetch(
                f"EXPLAIN (FORMAT JSON) "
                f"SELECT * FROM \"{schema}\".jobs WHERE metadata->>'batch_id' = $1",
                target_batch,
            )
        finally:
            await conn.close()

        from taskq._json import loads as _json_loads

        plan_data = _json_loads(explain_rows[0]["QUERY PLAN"])[0]["Plan"]
        node_type = plan_data.get("Node Type", "")
        assert node_type == "Seq Scan", (
            f"Expected Seq Scan for text-extraction form, got {node_type}"
        )


# ── 500-actor aggregated max_pending check ──────────────────────


@pytest.mark.integration
class TestTI7500ActorAggregatedMaxPending:
    """500-actor aggregated max_pending check (single round-trip)."""

    async def test_500_actors_single_count_pending_call(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.backend.postgres import PostgresBackend
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_ti7"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        mp_actors: list[Any] = []
        for i in range(500):
            fn = _make_mp_actor_fn(i)
            ref = actor(name=f"batch_mp_actor_{i}", max_pending=10)(fn)
            mp_actors.append(ref)

        items = [
            EnqueueItem(actor_ref=ref, payload=_Payload(value=i)) for i, ref in enumerate(mp_actors)
        ]

        count_pending_calls = 0
        original_count_pending = PostgresBackend.count_pending_jobs

        async def _counting_count_pending(
            backend_self: PostgresBackend, actors: list[str]
        ) -> dict[str, int]:
            nonlocal count_pending_calls
            count_pending_calls += 1
            return await original_count_pending(backend_self, actors)

        with patch.object(PostgresBackend, "count_pending_jobs", _counting_count_pending):
            async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
                handle = await tq.enqueue_batch(items)

        assert handle.size == 500
        assert count_pending_calls == 1


def _make_mp_actor_fn(idx: int) -> Any:
    """Return a unique async function for each actor index."""
    ns: dict[str, Any] = {"_Payload": _Payload}
    exec(  # noqa: S102  Why: need distinct function objects per actor; no user input reaches exec
        f"async def _mp_fn_{idx}(_p: _Payload) -> None: pass",
        ns,
    )
    return ns[f"_mp_fn_{idx}"]


# ── 1000-item batch performance ──────────────────────────────────


@pytest.mark.integration
class TestTC2ThousandItemBatchPerformance:
    """1000-item batch performance — completes within 5 seconds."""

    @pytest.mark.slow  # perf tier, not a correctness oracle — relaxed bound under load
    async def test_1000_items_within_5s(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tc2"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items = [_make_item(i) for i in range(1000)]
        start = time.monotonic()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            handle = await tq.enqueue_batch(items)
        elapsed = time.monotonic() - start

        # Functional oracle is handle.size; the wall-clock bound is a generous
        # perf sanity check (widened from 5s) to survive parallel-test load
        # (pytest -n 4) without false failures.
        assert handle.size == 1000
        assert elapsed < 30.0, f"1000-item batch took {elapsed:.2f}s, expected < 30s"


# ── Hypothesis batch size invariant ──────────────────────────────


class TestTP1HypothesisBatchSizeInvariant:
    """Hypothesis batch size invariant — size matches input, distinct IDs, same batch_id."""

    @given(
        items=st.lists(
            st.builds(EnqueueItem, actor_ref=st.just(_test_actor), payload=st.builds(_Payload)),
            min_size=1,
            max_size=1000,
        )
    )
    @settings(max_examples=50)
    async def test_batch_size_invariant(self, items: list[EnqueueItem]) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        handle = await client.enqueue_batch(items)

        assert handle.size == len(items)
        assert len(handle.job_handles) == len(items)
        job_ids = [h.job_id for h in handle.job_handles]
        assert len(set(job_ids)) == len(job_ids), "job_ids must be distinct"

        batch_id_str = str(handle.batch_id)
        for h in handle.job_handles:
            row = await backend.get(h.job_id)
            assert row is not None
            assert row.metadata.get("batch_id") == batch_id_str


# ── Mixed valid/invalid payloads fail entirely ───────────────────


@pytest.mark.integration
class TestTN1MixedValidInvalidPayloadsFailEntirely:
    """Mixed valid/invalid payloads — entire batch rejected, no partial insert."""

    async def test_no_partial_insert(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tn1"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        class _BadPayload(BaseModel):
            name: str = "bad"

        items = [_make_item(i) for i in range(5)]
        items.append(EnqueueItem(actor_ref=_test_actor, payload=_BadPayload()))

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(PayloadValidationError):
                await tq.enqueue_batch(items)

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE actor = $1',
                _test_actor.name,
            )
        finally:
            await conn.close()

        assert count == 0


# ── MaxPendingExceededError when max_pending exceeded ────────────


@pytest.mark.integration
class TestTN2MaxPendingExceededError:
    """MaxPendingExceededError when max_pending exceeded — all-or-nothing."""

    async def test_max_pending_exceeded_raises(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tn2"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        @actor(name="batch_mp_limited_actor", max_pending=5)
        async def _limited_actor(_p: _Payload) -> None:
            pass

        items = [
            EnqueueItem(actor_ref=_limited_actor, payload=_Payload(value=i)) for i in range(10)
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(MaxPendingExceededError) as exc_info:
                await tq.enqueue_batch(items)

        assert exc_info.value.actor == _limited_actor.name
        assert isinstance(exc_info.value, MaxPendingExceededError)

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')
        finally:
            await conn.close()

        assert count == 0


# ── Empty batch raises ValueError before DB ─────────────────────


@pytest.mark.integration
class TestTN3EmptyBatchRaisesValueErrorBeforeDB:
    """Empty batch raises ValueError before DB interaction."""

    async def test_empty_batch_no_db_call(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.backend.postgres import PostgresBackend
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tn3"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        enqueue_batch_calls = 0
        original_enqueue_batch = PostgresBackend.enqueue_batch

        async def _counting_enqueue_batch(
            backend_self: PostgresBackend,
            args_list: list[object],
            *,
            connection: object | None = None,
        ) -> list[object]:
            nonlocal enqueue_batch_calls
            enqueue_batch_calls += 1
            return await original_enqueue_batch(backend_self, args_list, connection=connection)  # type: ignore[arg-type]  # Why: wrapper delegates with same args

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with patch.object(PostgresBackend, "enqueue_batch", _counting_enqueue_batch):
                with pytest.raises(ValueError, match="empty"):
                    await tq.enqueue_batch([])

        assert enqueue_batch_calls == 0


# ── Oversized batch raises ValueError before DB ──────────────────


@pytest.mark.integration
class TestTN4OversizedBatchRaisesValueErrorBeforeDB:
    """Oversized batch (1001 items) raises ValueError before DB interaction."""

    async def test_1001_items_no_db_call(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.backend.postgres import PostgresBackend
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tn4"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        enqueue_batch_calls = 0
        original_enqueue_batch = PostgresBackend.enqueue_batch

        async def _counting_enqueue_batch(
            backend_self: PostgresBackend,
            args_list: list[object],
            *,
            connection: object | None = None,
        ) -> list[object]:
            nonlocal enqueue_batch_calls
            enqueue_batch_calls += 1
            return await original_enqueue_batch(backend_self, args_list, connection=connection)  # type: ignore[arg-type]  # Why: wrapper delegates with same args

        items = [_make_item(i) for i in range(1001)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with patch.object(PostgresBackend, "enqueue_batch", _counting_enqueue_batch):
                with pytest.raises(ValueError, match="1000"):
                    await tq.enqueue_batch(items)

        assert enqueue_batch_calls == 0


# ── Exactly 1000 items succeeds (integration) ───────────────────


@pytest.mark.integration
class TestTN5Exactly1000ItemsSucceedsIntegration:
    """Exactly 1000 items succeeds against real PG (UNNEST INSERT handles 1000 rows)."""

    async def test_1000_items_integration(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_tn5"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items = [_make_item(i) for i in range(1000)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            handle = await tq.enqueue_batch(items)

        assert handle.size == 1000

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE metadata @> $1::jsonb',
                dumps_str({"batch_id": str(handle.batch_id)}),
            )
        finally:
            await conn.close()

        assert count == 1000


class TestTU12IdempotencyKeyEmptyRaisesValueError:
    """item with idempotency_key="" raises ValueError before any I/O."""

    async def test_empty_key_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(actor_ref=_test_actor, payload=_Payload(), idempotency_key="")

        with pytest.raises(ValueError, match="empty"):
            await client.enqueue_batch([item])

    async def test_no_rows_inserted_on_empty_key(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(actor_ref=_test_actor, payload=_Payload(), idempotency_key="")

        with contextlib.suppress(ValueError):
            await client.enqueue_batch([item])

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]  # Why: test-only access to verify zero rows inserted


class TestTU13IdempotencyKeyWhitespaceRaisesValueError:
    """item with idempotency_key=" " raises ValueError before any I/O."""

    async def test_whitespace_key_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(actor_ref=_test_actor, payload=_Payload(), idempotency_key=" ")

        with pytest.raises(ValueError, match="whitespace"):
            await client.enqueue_batch([item])

    async def test_no_rows_inserted_on_whitespace_key(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(actor_ref=_test_actor, payload=_Payload(), idempotency_key=" ")

        with contextlib.suppress(ValueError):
            await client.enqueue_batch([item])

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]  # Why: test-only access to verify zero rows inserted


class TestTU14IdempotencyKeyTooLongRaisesValueError:
    """item with idempotency_key of 257 chars raises ValueError before any I/O."""

    async def test_257_char_key_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            idempotency_key="x" * 257,
        )

        with pytest.raises(ValueError, match="256"):
            await client.enqueue_batch([item])

    async def test_no_rows_inserted_on_too_long_key(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            idempotency_key="x" * 257,
        )

        with contextlib.suppress(ValueError):
            await client.enqueue_batch([item])

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]  # Why: test-only access to verify zero rows inserted


class TestTU5IdempotencyKeyCollisionWithinBatch:
    """Two EnqueueItems sharing the same idempotency_key in one enqueue_batch call."""

    async def test_both_handles_present(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        key = "batch-idem-key-shared"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key),
        ]

        handle = await client.enqueue_batch(items)

        assert len(handle.job_handles) == 2

    async def test_both_handles_point_to_same_job_id(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        key = "batch-idem-key-same-id"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key),
        ]

        handle = await client.enqueue_batch(items)

        assert handle.job_handles[0].job_id == handle.job_handles[1].job_id

    async def test_second_handle_was_existing(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        key = "batch-idem-key-was-existing"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=key),
        ]

        handle = await client.enqueue_batch(items)

        assert handle.job_handles[1].was_existing is True
