"""Tests for the enqueue_batch_fast COPY FROM primitive.

Unit tests run against InMemoryBackend with no external dependencies.
Integration tests require a live Postgres container and are marked
``pytest.mark.integration`` so ``pytest -m 'not integration'`` skips them.
"""

import contextlib
import time
from datetime import UTC, datetime
from uuid import UUID, uuid4

import pytest
from pydantic import BaseModel

from taskq import actor
from taskq.batch import EnqueueItem
from taskq.client._jobs import JobsClient
from taskq.exceptions import PayloadValidationError
from taskq.testing.clock import FakeClock
from taskq.testing.in_memory import InMemoryBackend

_START = datetime(2025, 1, 1, tzinfo=UTC)


# ── Test payloads and actors ───────────────────────────────────────────────


class _Payload(BaseModel):
    value: int = 0


@actor(name="batch_fast_test_actor")
async def _test_actor(_payload: _Payload) -> None:
    pass


def _make_backend() -> InMemoryBackend:
    return InMemoryBackend(clock=FakeClock(start=_START))


def _make_client(backend: InMemoryBackend) -> JobsClient:
    return JobsClient(backend=backend, clock=FakeClock(start=_START))


def _make_item(value: int = 0) -> EnqueueItem:
    return EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=value))


# ── Unit tests ─────────────────────────────────────────────────────────────


class TestTU1BasicBatchFastEnqueue:
    """enqueue_batch_fast returns correct count."""

    async def test_returns_count(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        count = await client.enqueue_batch_fast(items)

        assert isinstance(count, int)
        assert count == 3

    async def test_all_jobs_stored_in_backend(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(5)]

        count = await client.enqueue_batch_fast(items)

        assert count == 5
        assert len(backend._jobs) == 5  # type: ignore[reportPrivateUsage] # Why: test-only access


class TestTU2BatchIdInMetadata:
    """batch_id in metadata — all jobs have same metadata.batch_id."""

    async def test_all_jobs_have_same_batch_id(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(3)]

        count = await client.enqueue_batch_fast(items)

        assert count == 3
        for _job_id, row in list(backend._jobs.items()):  # type: ignore[reportPrivateUsage] # Why: test-only
            assert "batch_id" in row.metadata

    async def test_caller_metadata_merged(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        item = EnqueueItem(
            actor_ref=_test_actor,
            payload=_Payload(),
            metadata={"source": "api"},
        )

        count = await client.enqueue_batch_fast([item])

        assert count == 1
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.metadata.get("source") == "api"
            assert "batch_id" in row.metadata


class TestTU3AutoGeneratedBatchId:
    """Auto-generated batch_id — different for each call."""

    async def test_two_calls_get_different_batch_ids(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count1 = await client.enqueue_batch_fast([_make_item()])
        count2 = await client.enqueue_batch_fast([_make_item()])

        assert count1 == 1
        assert count2 == 1
        rows = list(backend._jobs.values())  # type: ignore[reportPrivateUsage]
        assert rows[0].metadata["batch_id"] != rows[1].metadata["batch_id"]


class TestTU4ExplicitBatchId:
    """Explicit batch_id — provided UUID used in all jobs."""

    async def test_explicit_batch_id_used(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        explicit_id = UUID("12345678-1234-5678-1234-567812345678")

        count = await client.enqueue_batch_fast([_make_item(), _make_item(1)], batch_id=explicit_id)

        assert count == 2
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.metadata.get("batch_id") == str(explicit_id)


class TestTU5EmptyListRaisesValueError:
    """Empty list raises ValueError."""

    async def test_empty_list_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        with pytest.raises(ValueError, match="empty"):
            await client.enqueue_batch_fast([])

    async def test_no_rows_inserted(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        with contextlib.suppress(ValueError):
            await client.enqueue_batch_fast([])

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]


class TestTU6TooManyItemsRaisesValueError:
    """50_001 items raises ValueError."""

    async def test_50001_items_raises(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(50_001)]

        with pytest.raises(ValueError, match="50 000"):
            await client.enqueue_batch_fast(items)


class TestTU7Exactly50000ItemsSucceeds:
    """Exactly 50_000 items succeeds (in-memory)."""

    async def test_50000_items_succeeds(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)
        items = [_make_item(i) for i in range(50_000)]

        count = await client.enqueue_batch_fast(items)

        assert count == 50_000


class TestTU8PayloadValidationFailure:
    """Payload validation failure — one bad item, entire batch rejected."""

    async def test_bad_payload_rejects_batch(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with pytest.raises(PayloadValidationError):
            await client.enqueue_batch_fast(items)

    async def test_no_rows_inserted_when_batch_fails(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        class _BadPayload(BaseModel):
            name: str = "bad"

        bad_item = EnqueueItem(actor_ref=_test_actor, payload=_BadPayload())
        items = [_make_item(0), bad_item, _make_item(2)]

        with contextlib.suppress(PayloadValidationError):
            await client.enqueue_batch_fast(items)

        assert len(backend._jobs) == 0  # type: ignore[reportPrivateUsage]


class TestTU9SingleItem:
    """Single item batch_fast."""

    async def test_single_item_returns_count_1(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count = await client.enqueue_batch_fast([_make_item(42)])

        assert count == 1
        row = next(iter(backend._jobs.values()))  # type: ignore[reportPrivateUsage]
        assert row.payload == {"value": 42}


class TestTU10StatusIsPending:
    """Jobs enqueued at current time have status 'pending'."""

    async def test_status_is_pending(self) -> None:
        backend = _make_backend()
        client = _make_client(backend)

        count = await client.enqueue_batch_fast([_make_item()])

        assert count == 1
        for row in backend._jobs.values():  # type: ignore[reportPrivateUsage]
            assert row.status == "pending"


# ── Integration tests ─────────────────────────────────────────────────────


@pytest.mark.integration
class TestTI1BasicPG:
    """basic COPY FROM insert against real PG."""

    async def test_100_items_count_correct(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti1"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        items = [_make_item(i) for i in range(100)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 100

        conn = await asyncpg.connect(pg_dsn)
        try:
            row_count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert row_count == 100
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI2BatchIdInAllRows:
    """All inserted rows carry the same batch_id."""

    async def test_500_items_same_batch_id(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti2"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        items = [_make_item(i) for i in range(500)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 500

        conn = await asyncpg.connect(pg_dsn)
        try:
            rows = await conn.fetch(
                f'SELECT id, metadata FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert len(rows) == 500
            for rec in rows:
                md = rec["metadata"]
                if isinstance(md, str):
                    from taskq._json import loads

                    md = loads(md)
                assert str(md.get("batch_id")) == str(batch_id)
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI3SingleItem:
    """single item COPY FROM against real PG."""

    async def test_single_item(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti3"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=99))],
                batch_id=batch_id,
            )

        assert count == 1

        conn = await asyncpg.connect(pg_dsn)
        try:
            rec = await conn.fetchrow(
                f'SELECT * FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert rec is not None
            assert rec["status"] in ("pending", "")
            assert rec["payload"] is not None
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI4LargeBatch10K:
    """10K item batch via COPY FROM."""

    async def test_10k_items(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti4"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        items = [_make_item(i % 1000) for i in range(10_000)]
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(items, batch_id=batch_id)

        assert count == 10_000

        conn = await asyncpg.connect(pg_dsn)
        try:
            row_count = await conn.fetchval(
                f'SELECT count(*) FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert row_count == 10_000
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI5PerformanceComparison:
    """COPY FROM faster than UNNEST for 1K items."""

    @pytest.mark.slow  # perf comparison, not correctness; relaxed multiplier under load
    async def test_copy_faster_than_unnest_1k(self, pg_dsn: str) -> None:
        """For 1K items (max for enqueue_batch), COPY FROM must be faster than UNNEST."""
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti5"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items_1k = [_make_item(i % 1000) for i in range(1_000)]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Time COPY FROM
            batch_id_fast = uuid4()
            start = time.monotonic()
            count_fast = await tq.enqueue_batch_fast(items_1k, batch_id=batch_id_fast)
            elapsed_fast = time.monotonic() - start
            assert count_fast == 1_000

            # Clean up inserted rows
            conn = await asyncpg.connect(pg_dsn)
            try:
                await conn.execute(
                    f'DELETE FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                    dumps_str({"batch_id": str(batch_id_fast)}),
                )
            finally:
                await conn.close()

            # Time UNNEST (regular enqueue_batch)
            batch_id_unnest = uuid4()
            start = time.monotonic()
            handle = await tq.enqueue_batch(items_1k, batch_id=batch_id_unnest)
            elapsed_unnest = time.monotonic() - start
            assert handle.size == 1_000

        assert elapsed_fast <= elapsed_unnest * 20, (
            f"COPY FROM ({elapsed_fast:.3f}s) should be competitive with "
            f"UNNEST ({elapsed_unnest:.3f}s) for 1K items"
        )


@pytest.mark.integration
class TestTI6PerformanceComparison4000:
    """COPY FROM faster than UNNEST for 1K items (second run)."""

    @pytest.mark.slow  # perf comparison, not correctness; relaxed multiplier under load
    async def test_copy_faster_than_unnest_1k_second(self, pg_dsn: str) -> None:
        """For 1K items, COPY FROM must be faster than UNNEST (repeatability)."""
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti6"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        items_1k = [_make_item(i % 1000) for i in range(1_000)]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            # Time COPY FROM
            batch_id_fast = uuid4()
            start = time.monotonic()
            count_fast = await tq.enqueue_batch_fast(items_1k, batch_id=batch_id_fast)
            elapsed_fast = time.monotonic() - start
            assert count_fast == 1_000

            # Clean up
            conn = await asyncpg.connect(pg_dsn)
            try:
                await conn.execute(
                    f'DELETE FROM "{schema}".jobs WHERE metadata @> $1::jsonb',  # noqa: S608
                    dumps_str({"batch_id": str(batch_id_fast)}),
                )
            finally:
                await conn.close()

            # Time UNNEST
            batch_id_unnest = uuid4()
            start = time.monotonic()
            handle = await tq.enqueue_batch(items_1k, batch_id=batch_id_unnest)
            elapsed_unnest = time.monotonic() - start
            assert handle.size == 1_000

        assert elapsed_fast <= elapsed_unnest * 20, (
            f"COPY FROM ({elapsed_fast:.3f}s) should be competitive with "
            f"UNNEST ({elapsed_unnest:.3f}s) for 1K items"
        )


@pytest.mark.integration
class TestTI7TransactionalBatchFast:
    """Transactional batch_fast — rollback means no rows."""

    async def test_rollback_means_no_rows(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti7"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            tx_conn = await asyncpg.connect(pg_dsn)
            tr = tx_conn.transaction()
            await tr.start()
            try:
                await tq.enqueue_batch_fast(
                    [_make_item(i) for i in range(3)],
                    batch_id=batch_id,
                    connection=tx_conn,
                )
            finally:
                await tr.rollback()
                await tx_conn.close()

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI8DuplicateIdempotencyKeyFails:
    """Duplicate idempotency_key aborts the entire COPY batch."""

    async def test_duplicate_key_fails_entire_batch(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti8"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        batch_id = uuid4()
        dup_key = f"dup-key-{uuid4()}"
        items = [
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), idempotency_key=dup_key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=2), idempotency_key=dup_key),
            EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=3)),
        ]

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(asyncpg.UniqueViolationError):
                await tq.enqueue_batch_fast(items, batch_id=batch_id)

        # Verify no rows inserted
        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTI9PayloadValidationFailureIntegration:
    """Payload validation failure — entire batch rejected, no partial insert."""

    async def test_no_partial_insert(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_ti9"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        class _BadPayload(BaseModel):
            name: str = "bad"

        items = [_make_item(i) for i in range(5)]
        items.append(EnqueueItem(actor_ref=_test_actor, payload=_BadPayload()))

        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            with pytest.raises(PayloadValidationError):
                await tq.enqueue_batch_fast(items)

        conn = await asyncpg.connect(pg_dsn)
        try:
            count = await conn.fetchval(f'SELECT count(*) FROM "{schema}".jobs')  # noqa: S608
            assert count == 0
        finally:
            await conn.close()


@pytest.mark.integration
class TestTIPastScheduledAtNormalized:
    """Past scheduled_at is normalized to now() — matches enqueue/enqueue_batch.

    Regression: enqueue_batch_fast stored the stale past timestamp instead
    of normalizing it to the batch clock like the regular enqueue path
    (which uses ``COALESCE($N, now())``).
    """

    async def test_past_scheduled_at_not_stored_stale(self, pg_dsn: str) -> None:
        import asyncpg

        from taskq import TaskQ
        from taskq._json import dumps_str
        from taskq.migrate import apply_pending

        schema = "taskq_test_batch_fast_past_scheduled"
        conn = await asyncpg.connect(pg_dsn)
        try:
            await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
            await apply_pending(conn, schema=schema)
        finally:
            await conn.close()

        # A scheduled_at well in the past relative to the live PG clock.
        past = _START
        batch_id = uuid4()
        async with TaskQ(dsn=pg_dsn, schema=schema) as tq:
            count = await tq.enqueue_batch_fast(
                [EnqueueItem(actor_ref=_test_actor, payload=_Payload(value=1), scheduled_at=past)],
                batch_id=batch_id,
            )

        assert count == 1

        conn = await asyncpg.connect(pg_dsn)
        try:
            rec = await conn.fetchrow(
                f'SELECT status, scheduled_at FROM "{schema}".jobs '  # noqa: S608
                f"WHERE metadata @> $1::jsonb",
                dumps_str({"batch_id": str(batch_id)}),
            )
            assert rec is not None
            assert rec["status"] == "pending"
            assert rec["scheduled_at"] != past
        finally:
            await conn.close()
