"""Tests for TaskQ.watch_reclaims() and its transport helpers
(_watch_reclaims_poll, _watch_reclaims_pg).

Unit tests run with ``pytest -m "not integration"`` — no Docker — using
:class:`InMemoryBackend`, following the pattern already established in
test_stream.py for TaskQ.stream().

Integration tests require Docker/testcontainers and are individually
decorated with ``@pytest.mark.integration``.

Covers:
- Poll-only transport (no DSN/listen source): events are yielded in
  ascending event_id order; the poll_timeout sleep branch is exercised
  when nothing new is available; resumption via after_id does not
  re-yield already-seen events.
- PG LISTEN transport: a real crash-reclaim is delivered promptly
  (NOTIFY-driven), not merely eventually via the poll-timeout fallback.
- Chaos — the LISTEN connection is killed mid-stream (pg_terminate_backend,
  same technique as test_stream.py's PG-LISTEN chaos test); the generator
  falls back to polling and keeps delivering correctly.
"""

# ruff: noqa: S608 Why: schema name is generated by new_base62()/validated by
# the migration runner's _IDENT_RE; asyncpg has no parameter binding for
# identifiers. Same suppression as test_stream.py.

import asyncio
import contextlib
import shutil
from datetime import UTC, datetime, timedelta
from typing import Any
from uuid import UUID

import asyncpg
import pytest
import structlog

from taskq._ids import new_base62, new_uuid
from taskq.backend._protocol import EventRow, JobId
from taskq.client._jobs import JobsClient
from taskq.client._taskq import TaskQ, _watch_reclaims_pg, _watch_reclaims_poll
from taskq.settings import TaskQSettings
from taskq.testing.clock import FakeClock
from taskq.testing.in_memory import InMemoryBackend
from taskq.testing.jobs import make_enqueue_args

_UNIT_SCHEMA_LABEL = "taskq_test"
_START = datetime(2025, 1, 1, tzinfo=UTC)
_GRACE = timedelta(seconds=30)


def _make_backend() -> InMemoryBackend:
    return InMemoryBackend(clock=FakeClock(start=_START))


def _make_client(backend: InMemoryBackend) -> JobsClient:
    settings = TaskQSettings.load_from_dict({"TASKQ_SCHEMA_NAME": _UNIT_SCHEMA_LABEL})
    return JobsClient(backend, settings=settings)


def _inject_poll_only_tq(backend: InMemoryBackend, *, poll_timeout: float = 30.0) -> TaskQ:
    """Construct a TaskQ with no DSN/listen source, forcing watch_reclaims()
    onto the plain poll loop — mirrors test_stream.py's _inject_tq, but sets
    every transport-selecting attribute explicitly since watch_reclaims()
    (unlike stream() on a terminal/missing job) always reaches the
    transport-dispatch branch.
    """
    tq = TaskQ.__new__(TaskQ)
    tq._dsn = None
    tq._pool = None
    tq._schema = _UNIT_SCHEMA_LABEL
    tq._min_pool_size = 1
    tq._max_pool_size = 5
    tq._redis_url = None
    tq._redis_client = None
    tq._pg_conn_factory = None
    tq._listen_conn = None
    tq._poll_timeout = poll_timeout
    tq._owns_pool = True
    tq._client = _make_client(backend)
    return tq


async def _make_running_row(
    backend: InMemoryBackend,
    *,
    max_attempts: int = 3,
    retry_kind: str = "transient",
) -> JobId:
    """Enqueue a job and manually flip it to running with an expired lock,
    then reclaim it — leaves one crash-reclaim event in the backend's
    event log for watch_reclaims()/poll_reclaim_events() to observe.
    """
    from dataclasses import replace as _replace

    args = make_enqueue_args(
        actor="watch_reclaims_test_actor",
        queue="default",
        payload={},
        scheduled_at=_START,
        max_attempts=max_attempts,
        retry_kind=retry_kind,  # type: ignore[arg-type]  # Why: test helper accepts the same RetryKind literals as the real EnqueueArgs
        priority=0,
        schedule_to_close=None,
    )
    row = await backend.enqueue(args)
    job_id = row.id

    worker_id = backend._worker_id  # type: ignore[reportPrivateUsage]  # Why: test-only private access
    running_row = _replace(
        row,
        status="running",
        locked_by_worker=worker_id,
        lock_expires_at=_START - timedelta(seconds=1),
        started_at=_START,
        last_heartbeat_at=_START,
    )
    backend._jobs[job_id] = running_row  # type: ignore[reportPrivateUsage]  # Why: test-only private access

    backend.advance_clock_to(_START + timedelta(seconds=1))
    count = await backend.reclaim_expired_locks(_GRACE, _GRACE)
    assert count == 1
    return job_id


async def _collect(gen: Any, *, n: int) -> list[EventRow]:
    """Collect exactly *n* items from an unbounded async generator, then
    stop iterating (closing it via aclosing semantics). Callers wrap this
    in ``asyncio.wait_for`` for an overall deadline."""
    import contextlib

    collected: list[EventRow] = []
    async with contextlib.aclosing(gen) as agen:
        async for evt in agen:
            collected.append(evt)
            if len(collected) >= n:
                break
    return collected


async def _wait_for_log(captured: list[dict[str, Any]], event: str) -> None:
    """Poll a structlog ``capture_logs()`` list until an entry named
    *event* appears — proof the generator actually reached the code path
    that emits it.  Never substitute a bare sleep: without this wait a
    test can pass while the path under test never runs."""
    deadline = asyncio.get_running_loop().time() + 5.0
    while not any(e["event"] == event for e in captured):
        assert asyncio.get_running_loop().time() < deadline, (
            f"generator never logged {event!r} — the code path under test was never entered"
        )
        await asyncio.sleep(0.01)


# ── Poll-only transport (unit, no Docker) ──────────────────────────


async def test_watch_reclaims_poll_only_yields_ascending() -> None:
    """No DSN/listen source: watch_reclaims() falls back to the plain
    poll loop and yields crash-reclaim events in ascending event_id
    order."""
    backend = _make_backend()
    await _make_running_row(backend)
    await _make_running_row(backend)

    tq = _inject_poll_only_tq(backend, poll_timeout=0.05)
    events = await asyncio.wait_for(_collect(tq.watch_reclaims(after_id=0), n=2), timeout=5.0)

    assert len(events) == 2
    assert events[0].event_id < events[1].event_id
    assert all(e.detail["reason"] == "lock_expired" for e in events)


async def test_watch_reclaims_poll_timeout_sleep_branch(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """When nothing new is available, the poll loop sleeps poll_timeout
    between polls — pinned by counting polls over a fixed window: at
    poll_timeout=0.1 with an event arriving at ~0.25s only a handful of
    polls can have run, where a busy-repoll (the sleep regressed away)
    would have burned thousands in the same window."""
    backend = _make_backend()
    tq = _inject_poll_only_tq(backend, poll_timeout=0.1)

    calls = {"n": 0}
    real_poll = backend.poll_reclaim_events

    async def _counting_poll(after_id: int, *args: Any, **kwargs: Any) -> Any:
        calls["n"] += 1
        return await real_poll(after_id, *args, **kwargs)

    monkeypatch.setattr(backend, "poll_reclaim_events", _counting_poll)

    gen = tq.watch_reclaims(after_id=0)

    async def _produce_after_delay() -> None:
        await asyncio.sleep(0.25)
        await _make_running_row(backend)

    producer = asyncio.create_task(_produce_after_delay())
    try:
        events = await asyncio.wait_for(_collect(gen, n=1), timeout=5.0)
        assert len(events) == 1
    finally:
        await producer

    assert calls["n"] <= 25, (
        f"expected ~4 polls at poll_timeout=0.1; got {calls['n']} — either the "
        "sleep regressed away (busy-repoll: observed ~120k polls in this window) "
        "or the event loop stalled"
    )


async def test_watch_reclaims_resumption_does_not_replay() -> None:
    """Calling watch_reclaims(after_id=N) after a previous call yielded up
    to event_id N must not re-yield events with event_id <= N."""
    backend = _make_backend()
    await _make_running_row(backend)
    await _make_running_row(backend)

    tq = _inject_poll_only_tq(backend, poll_timeout=0.05)

    first_batch = await asyncio.wait_for(_collect(tq.watch_reclaims(after_id=0), n=2), timeout=5.0)
    assert len(first_batch) == 2
    last_seen = first_batch[-1].event_id

    await _make_running_row(backend)

    second_batch = await asyncio.wait_for(
        _collect(tq.watch_reclaims(after_id=last_seen), n=1), timeout=5.0
    )
    assert len(second_batch) == 1
    assert second_batch[0].event_id > last_seen
    assert all(e.event_id > last_seen for e in second_batch)


# ── Visibility-delay risk probe (unit, no Docker) ─────────────────


async def test_watch_reclaims_visibility_risk_probe_warns_by_default(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The watcher wires check_reclaim_visibility_delay_risk in by default
    (the operator does not have to know the diagnostic exists): when the
    backend reports a job_events writer transaction open longer than the
    margin, the watcher logs a loud structured
    'watch-reclaims-visibility-delay-at-risk' warning on its own cadence."""
    from taskq.backend._protocol import LongRunningJobEventsWriter

    monkeypatch.setattr("taskq.client._taskq._VISIBILITY_RISK_CHECK_INTERVAL", 0.0)
    backend = _make_backend()

    async def _fake_check(*, visibility_delay: Any = None) -> list[Any]:
        return [
            LongRunningJobEventsWriter(
                pid=4242,
                xact_start=_START,
                xact_age_seconds=7.5,
            )
        ]

    # raising=False: InMemoryBackend has no such method — that is exactly
    # why the probe must discover it via getattr at runtime.
    monkeypatch.setattr(backend, "check_reclaim_visibility_delay_risk", _fake_check, raising=False)

    tq = _inject_poll_only_tq(backend, poll_timeout=0.02)

    async def _produce_after_delay() -> None:
        await asyncio.sleep(0.1)
        await _make_running_row(backend)

    producer = asyncio.create_task(_produce_after_delay())
    with structlog.testing.capture_logs() as captured:
        try:
            events = await asyncio.wait_for(
                _collect(tq.watch_reclaims(after_id=0), n=1), timeout=5.0
            )
        finally:
            await producer

    assert len(events) == 1, "delivery must continue alongside the probe"
    warnings = [e for e in captured if e["event"] == "watch-reclaims-visibility-delay-at-risk"]
    assert warnings, "expected the built-in probe to warn about the long-open writer"
    assert warnings[0]["pid"] == 4242
    assert warnings[0]["xact_age_seconds"] == 7.5


async def test_watch_reclaims_visibility_risk_probe_failure_never_kills_watcher(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A failing probe (permissions on pg_locks, a transient pool error)
    is logged as 'watch-reclaims-visibility-risk-probe-failed' and
    swallowed — a monitoring path must never take down the delivery path
    it monitors."""
    monkeypatch.setattr("taskq.client._taskq._VISIBILITY_RISK_CHECK_INTERVAL", 0.0)
    backend = _make_backend()

    async def _failing_check(*, visibility_delay: Any = None) -> list[Any]:
        raise OSError("simulated probe failure")

    # raising=False: see the companion test above.
    monkeypatch.setattr(
        backend, "check_reclaim_visibility_delay_risk", _failing_check, raising=False
    )

    tq = _inject_poll_only_tq(backend, poll_timeout=0.02)

    async def _produce_after_delay() -> None:
        await asyncio.sleep(0.1)
        await _make_running_row(backend)

    producer = asyncio.create_task(_produce_after_delay())
    with structlog.testing.capture_logs() as captured:
        try:
            events = await asyncio.wait_for(
                _collect(tq.watch_reclaims(after_id=0), n=1), timeout=5.0
            )
        finally:
            await producer

    assert len(events) == 1, "probe failure must not interrupt delivery"
    assert any(e["event"] == "watch-reclaims-visibility-risk-probe-failed" for e in captured)


# ── PG LISTEN transport state machine (unit, fake connection) ──────


class _FakeListenConn:
    """Minimal asyncpg.Connection stand-in for _watch_reclaims_pg unit tests.

    Mirrors exactly the interaction surface the transport uses:
    add_listener / remove_listener / add/remove_termination_listener /
    is_closed / close.  kill() simulates a server-side drop
    (pg_terminate_backend): the connection dies, termination listeners
    fire, and — critically — no exception is ever raised into the
    consuming coroutine, matching real asyncpg behaviour.  This is why
    detection must go through is_closed() + the termination listener,
    not an except clause around the consume loop.
    """

    def __init__(self) -> None:
        self._closed = False
        self._notify_callbacks: list[tuple[str, Any]] = []
        self._termination_listeners: list[Any] = []
        self.listener_channels: list[str] = []
        self.close_calls = 0

    async def add_listener(self, channel: str, callback: Any) -> None:
        if self._closed:
            raise asyncpg.InterfaceError("connection is closed")
        self.listener_channels.append(channel)
        self._notify_callbacks.append((channel, callback))

    async def remove_listener(self, channel: str, callback: Any) -> None:
        self._notify_callbacks = [
            (ch, cb) for ch, cb in self._notify_callbacks if not (ch == channel and cb is callback)
        ]

    def add_termination_listener(self, callback: Any) -> None:
        self._termination_listeners.append(callback)

    def remove_termination_listener(self, callback: Any) -> None:
        if callback in self._termination_listeners:
            self._termination_listeners.remove(callback)

    def is_closed(self) -> bool:
        return self._closed

    async def close(self) -> None:
        self.close_calls += 1
        self._die()

    def kill(self) -> None:
        """Simulate pg_terminate_backend: the conn dies server-side."""
        self._die()

    def _die(self) -> None:
        if self._closed:
            return
        self._closed = True
        for cb in list(self._termination_listeners):
            cb(self)

    def fire_notify(self) -> None:
        for ch, cb in list(self._notify_callbacks):
            cb(self, 0, ch, "")


async def test_watch_reclaims_pg_reconnects_after_listen_conn_death(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Killing the dedicated LISTEN connection is *detected* (asyncpg never
    raises into the consume loop — notifications just stop), the generator
    falls back to polling, re-establishes the LISTEN connection via the
    factory after _RECONNECT_POLL_INTERVAL poll iterations, logs
    'watch-reclaims-listen-reconnected', and keeps delivering."""
    monkeypatch.setattr("taskq.client._taskq._RECONNECT_POLL_INTERVAL", 2)
    backend = _make_backend()
    client = _make_client(backend)
    conns: list[_FakeListenConn] = []

    async def _factory() -> _FakeListenConn:
        conn = _FakeListenConn()
        conns.append(conn)
        return conn

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.02,
        pg_conn_factory=_factory,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    with structlog.testing.capture_logs() as captured:
        task = asyncio.create_task(_collect(gen, n=1))
        await asyncio.sleep(0.05)  # first poll + LISTEN registration settle
        assert len(conns) == 1
        conns[0].kill()
        await asyncio.sleep(0.2)  # detection + fallback polls + reconnect (interval=2 @ 0.02s)
        await _make_running_row(backend)
        events = await asyncio.wait_for(task, timeout=5.0)

    assert len(events) == 1
    assert len(conns) == 2, "the dead LISTEN connection was never re-established"
    assert conns[1].listener_channels, "reconnected conn never re-registered LISTEN"
    assert any(e["event"] == "watch-reclaims-listen-reconnected" for e in captured)


async def test_watch_reclaims_pg_caller_owned_conn_death_permanent_poll_fallback() -> None:
    """A caller-supplied listen_conn cannot be reconnected (the caller owns
    its lifecycle): on death the generator logs
    'watch-reclaims-listen-connection-lost' once and settles into the
    permanent poll fallback — the documented limitation — still delivering
    events, without closing the caller's connection."""
    backend = _make_backend()
    client = _make_client(backend)
    conn = _FakeListenConn()

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.02,
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    with structlog.testing.capture_logs() as captured:
        task = asyncio.create_task(_collect(gen, n=1))
        await asyncio.sleep(0.05)
        conn.kill()
        await asyncio.sleep(0.1)
        await _make_running_row(backend)
        events = await asyncio.wait_for(task, timeout=5.0)

    assert len(events) == 1
    lost = [e for e in captured if e["event"] == "watch-reclaims-listen-connection-lost"]
    assert len(lost) == 1
    assert conn.close_calls == 0, "generator must not close a caller-owned connection"


async def test_watch_reclaims_pg_pool_error_propagates_not_misdiagnosed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """An InterfaceError raised by poll_reclaim_events is a *pool/backend*
    failure, not a LISTEN failure: it must propagate to the caller (who
    can resume from the last-seen cursor) rather than being swallowed by
    the listen-failure fallback, which would hide a real backend outage
    behind a 'watch-reclaims-listen-connection-lost' misdiagnosis."""
    backend = _make_backend()
    client = _make_client(backend)
    conn = _FakeListenConn()

    real_poll = backend.poll_reclaim_events
    calls = {"n": 0}

    async def _fail_second_call(after_id: int, *args: Any, **kwargs: Any) -> Any:
        calls["n"] += 1
        if calls["n"] == 2:
            raise asyncpg.InterfaceError("transient pool failure")
        return await real_poll(after_id, *args, **kwargs)

    monkeypatch.setattr(backend, "poll_reclaim_events", _fail_second_call)

    # poll_timeout is huge so the generator parks in wake.wait() after the
    # first (empty, successful) poll; fire_notify() then drives the
    # failure specifically through _catch_up_after_notify — the call site
    # the old except clause misdiagnosed as a LISTEN failure.
    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        30.0,
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )

    async def _first_event() -> EventRow:
        async with contextlib.aclosing(gen) as agen:
            async for evt in agen:
                return evt
        raise AssertionError("generator finished without yielding")

    task = asyncio.create_task(_first_event())
    await asyncio.sleep(0.05)  # first poll done; parked in wake.wait()
    conn.fire_notify()
    with pytest.raises(asyncpg.InterfaceError):
        await asyncio.wait_for(task, timeout=2.0)


async def test_watch_reclaims_pg_full_batch_drains_without_waiting() -> None:
    """A backlog larger than one batch drains immediately: after yielding
    a full batch the loop re-polls instead of waiting poll_timeout —
    otherwise a >100-event crash storm drains at ~100 events per
    poll_timeout (a minute for 250 events at the 30s default), in exactly
    the scenario watch_reclaims exists for."""
    backend = _make_backend()
    for _ in range(150):
        await _make_running_row(backend)
    client = _make_client(backend)
    conn = _FakeListenConn()  # alive the whole time; never fires a notify

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        30.0,  # poll_timeout deliberately huge: draining must not wait on it
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    events = await asyncio.wait_for(_collect(gen, n=150), timeout=5.0)

    assert len(events) == 150
    assert [e.event_id for e in events] == sorted(e.event_id for e in events)


async def test_watch_reclaims_pg_degraded_loop_drains_full_batches() -> None:
    """The caller-owned degraded (connection-lost) poll fallback drains
    backlogs at the same speed as the healthy loop: full batch →
    immediate re-poll, not a poll_timeout sleep.  A crash storm landing
    while the LISTEN connection is down must not take N/100 x
    poll_timeout to deliver.

    Ordering is the whole pin: the 250-event backlog is created only
    AFTER the 'watch-reclaims-listen-connection-lost' log line proves
    the generator is inside the fallback loop.  Events created before
    the kill would drain through the *healthy* loop's full-batch
    continue and the fallback loop would never run — an earlier revision
    of this test did exactly that and pinned nothing.

    poll_timeout is 1.0s by construction: the fallback sleeps one
    poll_timeout before its first poll, so with the full-batch re-poll
    the backlog drains in ~1 x poll_timeout; without it, three batches
    cost ~3 x poll_timeout — past the collection deadline."""
    backend = _make_backend()
    client = _make_client(backend)
    conn = _FakeListenConn()

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        1.0,
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    with structlog.testing.capture_logs() as captured:
        task = asyncio.create_task(_collect(gen, n=250))
        await asyncio.sleep(0.05)  # LISTEN registered, first (empty) poll done
        assert conn.listener_channels, (
            "generator never registered LISTEN — settle sleep insufficient"
        )
        conn.kill()  # into the caller-owned permanent poll fallback
        await _wait_for_log(captured, "watch-reclaims-listen-connection-lost")
        for _ in range(250):
            await _make_running_row(backend)
        events = await asyncio.wait_for(task, timeout=2.0)

    assert len(events) == 250
    assert [e.event_id for e in events] == sorted(e.event_id for e in events)


async def test_watch_reclaims_pg_owned_conn_degraded_loop_drains_full_batches(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Same pin as the caller-owned variant above, for the owned-conn
    (pg_conn_factory) degraded poll/reconnect loop: its full-batch →
    immediate re-poll must keep working while the LISTEN connection is
    down — until a reconnect succeeds this loop is the only live
    delivery path.  Reconnect attempts are gated far apart
    (_RECONNECT_POLL_INTERVAL huge) so the drain provably happens inside
    the degraded loop, which the final len(conns) == 1 assertion
    confirms."""
    monkeypatch.setattr("taskq.client._taskq._RECONNECT_POLL_INTERVAL", 1000)
    backend = _make_backend()
    client = _make_client(backend)
    conns: list[_FakeListenConn] = []

    async def _factory() -> _FakeListenConn:
        conn = _FakeListenConn()
        conns.append(conn)
        return conn

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        1.0,
        pg_conn_factory=_factory,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    with structlog.testing.capture_logs() as captured:
        task = asyncio.create_task(_collect(gen, n=250))
        await asyncio.sleep(0.05)  # factory conn opened, LISTEN registered
        assert len(conns) == 1
        conns[0].kill()  # into the owned-conn poll/reconnect fallback
        await _wait_for_log(captured, "watch-reclaims-listen-connection-lost")
        for _ in range(250):
            await _make_running_row(backend)
        events = await asyncio.wait_for(task, timeout=2.0)

    assert len(events) == 250
    assert [e.event_id for e in events] == sorted(e.event_id for e in events)
    assert len(conns) == 1, (
        "a reconnect fired mid-test — the drain did not happen in the degraded loop"
    )


async def test_watch_reclaims_pg_reconnect_attempt_is_timeboxed(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A hanging reconnect attempt must not stall the degraded poll loop —
    the only live delivery path at that point.  asyncpg.connect() defaults
    to a 60s timeout and a user pg_conn_factory is unbounded, so the
    attempt is capped at poll_timeout; a TimeoutError is just another
    failed attempt (warning, keep polling)."""
    monkeypatch.setattr("taskq.client._taskq._RECONNECT_POLL_INTERVAL", 2)
    backend = _make_backend()
    client = _make_client(backend)
    conns: list[_FakeListenConn] = []

    async def _factory() -> _FakeListenConn:
        if not conns:
            conn = _FakeListenConn()
            conns.append(conn)
            return conn
        await asyncio.sleep(30.0)  # hangs like a partitioned DSN/factory
        raise AssertionError("unreachable")

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.02,
        pg_conn_factory=_factory,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    task = asyncio.create_task(_collect(gen, n=1))
    await asyncio.sleep(0.05)
    conns[0].kill()
    await asyncio.sleep(0.2)  # several reconnect attempts, each capped at poll_timeout
    await _make_running_row(backend)
    events = await asyncio.wait_for(task, timeout=5.0)

    assert len(events) == 1


async def test_watch_reclaims_pg_reconnect_failure_warns_on_a_cadence(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Persistent reconnect failure must not go quiet after one warning:
    the first failure and every 10th subsequent failure log
    'watch-reclaims-reconnect-still-failing', matching the docstring's
    'logged at a cadence' promise — a multi-hour outage leaves evidence
    the watcher is still degraded without spamming every attempt."""
    monkeypatch.setattr("taskq.client._taskq._RECONNECT_POLL_INTERVAL", 1)
    backend = _make_backend()
    client = _make_client(backend)
    conns: list[_FakeListenConn] = []

    async def _factory() -> _FakeListenConn:
        if not conns:
            conn = _FakeListenConn()
            conns.append(conn)
            return conn
        raise ConnectionRefusedError("pg still down")

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.01,
        pg_conn_factory=_factory,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    with structlog.testing.capture_logs() as captured:
        task = asyncio.create_task(_collect(gen, n=1))
        await asyncio.sleep(0.05)
        conns[0].kill()
        await asyncio.sleep(0.7)  # ~50+ failed attempts at poll_timeout=0.01
        task.cancel()
        with contextlib.suppress(asyncio.CancelledError):
            await task

    warnings = [e for e in captured if e["event"] == "watch-reclaims-reconnect-still-failing"]
    assert len(warnings) >= 3, (
        f"expected cadence logging (attempts 1, 10, 20, ...), got {len(warnings)} warning(s)"
    )


class _UnlistenFailsConn(_FakeListenConn):
    """remove_listener raises — connection dropped mid-teardown."""

    async def remove_listener(self, channel: str, callback: Any) -> None:
        raise asyncpg.InterfaceError("connection dropped mid-teardown")


async def test_watch_reclaims_pg_teardown_removes_termination_listener_when_unlisten_fails() -> (
    None
):
    """If UNLISTEN fails during teardown (connection dropped mid-shutdown),
    the termination listener must STILL be removed — otherwise a shared,
    caller-owned listen_conn accumulates dead callbacks closing over dead
    generator frames on every watch_reclaims() call."""
    backend = _make_backend()
    client = _make_client(backend)
    conn = _UnlistenFailsConn()
    await _make_running_row(backend)

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.02,
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    events = await _collect(gen, n=1)

    assert len(events) == 1
    assert conn._termination_listeners == [], (
        "termination listener leaked on the caller's connection"
    )


async def test_watch_reclaims_pg_cancellation_inside_degraded_loop_closes_owned_conn() -> None:
    """Cancelling the consumer while the generator sits in the degraded
    poll/reconnect fallback runs the finally teardown: the owned (dead)
    connection is closed exactly once."""
    backend = _make_backend()
    client = _make_client(backend)
    conns: list[_FakeListenConn] = []

    async def _factory() -> _FakeListenConn:
        conn = _FakeListenConn()
        conns.append(conn)
        return conn

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        0.02,
        pg_conn_factory=_factory,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    task = asyncio.create_task(_collect(gen, n=1))
    await asyncio.sleep(0.05)
    conns[0].kill()
    await asyncio.sleep(0.1)  # generator is now parked in the degraded loop

    task.cancel()  # CancelledError unwinds through the fallback loop → finally
    with contextlib.suppress(asyncio.CancelledError):
        await task

    assert conns[0].close_calls == 1, "owned connection must be closed exactly once on teardown"


async def test_watch_reclaims_pg_notify_during_backlog_drain_not_discarded(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A NOTIFY arriving mid-drain must not be silently discarded by
    wake.clear(): after a full batch the loop re-polls, and if that poll
    still comes up empty (the notified row is inside the visibility
    margin) the pending wake must fire the wait immediately — otherwise
    delivery stalls up to poll_timeout for an event that DID notify.

    InMemoryBackend has no visibility margin, so the test simulates one
    from inside the poll wrapper (deterministically): the NOTIFY fires
    mid-drain of the first (full) batch, the new row commits right after,
    and exactly one subsequent poll withholds it as "inside the margin"."""
    backend = _make_backend()
    for _ in range(100):
        await _make_running_row(backend)
    client = _make_client(backend)
    conn = _FakeListenConn()

    real_poll = backend.poll_reclaim_events
    calls = {"n": 0}

    async def _withhold_one_poll(after_id: int, *args: Any, **kwargs: Any) -> Any:
        calls["n"] += 1
        if calls["n"] == 1:
            events = await real_poll(after_id, *args, **kwargs)
            # A new reclaim commits AND notifies while the loop is still
            # draining this batch — the wake must survive until the loop
            # next waits on it.
            conn.fire_notify()
            await _make_running_row(backend)
            return events
        if calls["n"] == 2:
            return []  # notified row still "inside the margin"
        return await real_poll(after_id, *args, **kwargs)

    monkeypatch.setattr(backend, "poll_reclaim_events", _withhold_one_poll)

    gen = _watch_reclaims_pg(
        None,
        _UNIT_SCHEMA_LABEL,
        client,
        30.0,  # poll_timeout huge: only a surviving wake beats the deadline
        listen_conn=conn,  # type: ignore[arg-type]  # Why: fake conn stand-in for asyncpg.Connection
    )
    events = await asyncio.wait_for(_collect(gen, n=101), timeout=3.0)

    assert len(events) == 101


# ── Visibility-risk probe (unit) ────────────────────────────────────


async def test_visibility_probe_hang_does_not_stall_delivery(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A hung visibility-risk probe (pool exhaustion, slow catalog scan)
    must not stall event delivery: the probe is timeboxed and its failure
    swallowed — a monitoring path never takes down the delivery path it
    monitors, by hanging any more than by raising."""
    monkeypatch.setattr("taskq.client._taskq._VISIBILITY_RISK_CHECK_INTERVAL", 0.0)
    # raising=False: the constant is introduced by the fix under test.
    monkeypatch.setattr("taskq.client._taskq._VISIBILITY_PROBE_TIMEOUT", 0.05, raising=False)
    backend = _make_backend()
    client = _make_client(backend)

    async def _hanging_check(*args: Any, **kwargs: Any) -> Any:
        await asyncio.sleep(30.0)

    monkeypatch.setattr(
        backend, "check_reclaim_visibility_delay_risk", _hanging_check, raising=False
    )

    gen = _watch_reclaims_poll(client, 0.02, after_id=0)

    async def _produce_after_first_probe() -> None:
        await asyncio.sleep(0.1)  # first (empty) poll has run; probe is now hung
        await _make_running_row(backend)

    producer = asyncio.create_task(_produce_after_first_probe())
    try:
        events = await asyncio.wait_for(_collect(gen, n=1), timeout=3.0)
        assert len(events) == 1
    finally:
        await producer


async def test_visibility_probe_runs_at_most_once_per_interval(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The probe is time-gated: with a nonzero interval it runs at most
    once per _VISIBILITY_RISK_CHECK_INTERVAL, never once per poll — one
    extra catalog query per watcher per interval, not on the hot path."""
    monkeypatch.setattr("taskq.client._taskq._VISIBILITY_RISK_CHECK_INTERVAL", 0.2)
    backend = _make_backend()
    client = _make_client(backend)
    calls = {"n": 0}

    async def _counting_check(*args: Any, **kwargs: Any) -> list[Any]:
        calls["n"] += 1
        return []

    monkeypatch.setattr(
        backend, "check_reclaim_visibility_delay_risk", _counting_check, raising=False
    )

    gen = _watch_reclaims_poll(client, 0.01, after_id=0)

    async def _spin() -> None:
        async with contextlib.aclosing(gen) as agen:
            async for _ in agen:
                pass

    task = asyncio.create_task(_spin())
    await asyncio.sleep(0.55)
    task.cancel()
    with contextlib.suppress(asyncio.CancelledError):
        await task

    # Gate opens at t≈0.2 and t≈0.4 → 2 probes (±1 for scheduling jitter);
    # ~55 poll iterations without gating would mean ~55 probes.
    assert 1 <= calls["n"] <= 3


# ── PG LISTEN transport + chaos (integration, Docker) ──────────────


async def _open_taskq_pg(
    pg_dsn: str,
    *,
    schema: str,
    poll_timeout: float = 5.0,
) -> tuple[TaskQ, UUID]:
    """Open a TaskQ against the PG container with schema isolation.

    Mirrors test_stream.py's helper of the same name.
    """
    from taskq.migrate import apply_pending

    conn = await asyncpg.connect(pg_dsn)
    try:
        await conn.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
        await apply_pending(conn, schema=schema)
    finally:
        await conn.close()

    tq = TaskQ(dsn=pg_dsn, schema=schema, poll_timeout=poll_timeout)
    await tq.open()

    worker_id = new_uuid()
    assert tq._client is not None
    async with tq._pool.acquire() as c:  # type: ignore[union-attr] # Why: tq._pool is set by open()
        await c.execute(
            f'INSERT INTO "{schema}".workers (id, hostname, pid, queues) '
            "VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO NOTHING",
            worker_id,
            "test-host",
            12345,
            ["default"],
        )
    return tq, worker_id


@pytest.mark.integration
async def test_watch_reclaims_pg_listen_delivers_promptly(pg_dsn: str) -> None:
    """A real crash-reclaim (force-expired lock + Sweep 1) is delivered
    via watch_reclaims() well before poll_timeout would have elapsed on
    its own — i.e. the NOTIFY-driven wakeup (plus its bounded post-notify
    catch-up poll, which bridges RECLAIM_EVENT_VISIBILITY_DELAY), not
    just the poll-timeout fallback, is what delivered it. poll_timeout is
    deliberately large (30s, TaskQ's real default) so that a poll-only
    fallback would clearly not have delivered this quickly."""
    from taskq.backend.postgres import PostgresBackend
    from taskq.testing.pg import create_running_job

    schema = f"tst_{new_base62()}".lower()
    tq, worker_id = await _open_taskq_pg(pg_dsn, schema=schema, poll_timeout=30.0)
    try:
        assert tq._pool is not None
        async with tq._pool.acquire() as conn:
            # _open_taskq_pg already inserted the worker row for worker_id.
            job_id = await create_running_job(
                conn,
                schema,
                worker_id,
                lock_expires_at=datetime.now(UTC) - timedelta(seconds=10),
                max_attempts=1,
                retry_kind="transient",
                attempt=1,
            )

        loop_start = asyncio.get_event_loop().time()

        async def _sweep_soon() -> None:
            await asyncio.sleep(0.2)
            assert tq._pool is not None
            async with tq._pool.acquire() as conn:
                await PostgresBackend.sweep_expired_locks(
                    conn,
                    _GRACE,
                    _GRACE,
                    schema=schema,
                )

        sweep_task = asyncio.create_task(_sweep_soon())
        try:
            events = await asyncio.wait_for(
                _collect(tq.watch_reclaims(after_id=0), n=1), timeout=8.0
            )
        finally:
            await sweep_task

        elapsed = asyncio.get_event_loop().time() - loop_start
        assert len(events) == 1
        assert events[0].job_id == JobId(job_id)
        # Comfortably under poll_timeout (30s) — proves NOTIFY plus its
        # bounded catch-up poll delivered this, not the poll-timeout
        # fallback alone (which would have taken ~30s).
        assert elapsed < 6.0
    finally:
        await tq.close()


@pytest.mark.integration
async def test_watch_reclaims_survives_listen_connection_kill(pg_dsn: str) -> None:
    """pg_terminate_backend kills watch_reclaims()'s dedicated LISTEN
    connection mid-stream (same technique as test_stream.py's
    test_tc1_pg_listen_connection_dropped_stream_recovers).  asyncpg does
    NOT raise into the consume loop when this happens — the death is
    detected via the termination listener / is_closed() checks; the
    generator falls back to polling and delivers the pending event, then
    RE-ESTABLISHES the LISTEN connection — asserted via the
    'watch-reclaims-listen-reconnected' log line AND a live LISTEN pid in
    pg_stat_activity, so the reconnect machinery cannot silently rot —
    and keeps delivering afterwards."""
    from taskq.backend.postgres import PostgresBackend
    from taskq.testing.pg import create_running_job

    schema = f"tst_{new_base62()}".lower()
    tq, worker_id = await _open_taskq_pg(pg_dsn, schema=schema, poll_timeout=0.3)
    try:
        assert tq._pool is not None
        # _open_taskq_pg already inserted the worker row for worker_id.

        gen = tq.watch_reclaims(after_id=0)

        with structlog.testing.capture_logs() as captured:
            # Start consuming in the background so the LISTEN connection is
            # actually opened before we kill it.
            collect_task = asyncio.create_task(asyncio.wait_for(_collect(gen, n=2), timeout=30.0))
            await asyncio.sleep(0.2)

            assert tq._pool is not None
            async with tq._pool.acquire() as conn:
                listen_pids = await conn.fetch(
                    "SELECT pid FROM pg_stat_activity "
                    "WHERE query LIKE '%LISTEN%' AND datname = current_database() "
                    "AND pid != pg_backend_pid()"
                )
            killed_pids = {int(row["pid"]) for row in listen_pids}
            assert killed_pids, "no LISTEN connection found to kill"
            psql_path = shutil.which("psql")
            assert psql_path is not None, "psql not found on PATH"
            for pid in killed_pids:
                proc = await asyncio.create_subprocess_exec(
                    psql_path,
                    pg_dsn,
                    "-c",
                    f"SELECT pg_terminate_backend({pid})",
                    stdout=asyncio.subprocess.DEVNULL,
                    stderr=asyncio.subprocess.DEVNULL,
                )
                await proc.wait()

            await asyncio.sleep(0.3)

            # Produce the first crash-reclaim event; the poll-fallback
            # loop (not the dead LISTEN connection) must still pick it up.
            async with tq._pool.acquire() as conn:
                job_id_1 = await create_running_job(
                    conn,
                    schema,
                    worker_id,
                    lock_expires_at=datetime.now(UTC) - timedelta(seconds=10),
                    max_attempts=1,
                    retry_kind="transient",
                    attempt=1,
                )
                await PostgresBackend.sweep_expired_locks(
                    conn,
                    _GRACE,
                    _GRACE,
                    schema=schema,
                )

            # The generator must now detect the dead connection, fall back
            # to polling, and re-establish the LISTEN connection (every
            # _RECONNECT_POLL_INTERVAL poll iterations).  Assert on the
            # recovery log line — without it this test passed historically
            # without ever entering the reconnect branch.
            deadline = asyncio.get_running_loop().time() + 15.0
            while not any(e["event"] == "watch-reclaims-listen-reconnected" for e in captured):
                assert asyncio.get_running_loop().time() < deadline, (
                    "LISTEN connection was never re-established "
                    "(no 'watch-reclaims-listen-reconnected' log line)"
                )
                await asyncio.sleep(0.1)

            # And a real, live LISTEN connection must exist — not just a
            # log line claiming one does.
            async with tq._pool.acquire() as conn:
                relisten = await conn.fetch(
                    "SELECT pid FROM pg_stat_activity "
                    "WHERE query LIKE '%LISTEN%' AND datname = current_database() "
                    "AND pid != pg_backend_pid()"
                )
            assert relisten, "no live LISTEN connection after 'reconnected' log line"
            assert killed_pids.isdisjoint({int(row["pid"]) for row in relisten})

            # Produce a second event — the re-established stream must keep
            # delivering.
            async with tq._pool.acquire() as conn:
                job_id_2 = await create_running_job(
                    conn,
                    schema,
                    worker_id,
                    lock_expires_at=datetime.now(UTC) - timedelta(seconds=10),
                    max_attempts=1,
                    retry_kind="transient",
                    attempt=1,
                )
                await PostgresBackend.sweep_expired_locks(
                    conn,
                    _GRACE,
                    _GRACE,
                    schema=schema,
                )

            events = await collect_task

        assert len(events) == 2
        assert {events[0].job_id, events[1].job_id} == {JobId(job_id_1), JobId(job_id_2)}
    finally:
        await tq.close()
