# generated by datamodel-codegen:
#   filename:  advanced.DeduplicatedPayload.json
#   timestamp: 2026-09-13T00:17:40+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DeduplicatedPayload(BaseModel):
    key: str = Field('default', title='Key')
