# generated by datamodel-codegen:
#   filename:  advanced.SumResult.json
#   timestamp: 2026-09-13T00:17:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SumResult(BaseModel):
    total: int = Field(..., title='Total')
