# generated by datamodel-codegen:
#   filename:  basic.CounterPayload.json
#   timestamp: 2026-09-13T00:17:42+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CounterPayload(BaseModel):
    n: int = Field(10, title='N')
