# generated by datamodel-codegen:
#   filename:  chained.PipelinePayload.json
#   timestamp: 2026-09-13T00:17:44+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class PipelinePayload(BaseModel):
    text: str = Field('hello', title='Text')
