# generated by datamodel-codegen:
#   filename:  di.DbLookupPayload.json
#   timestamp: 2026-09-13T00:17:44+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DbLookupPayload(BaseModel):
    item_id: int = Field(1, title='Item Id')
