# generated by datamodel-codegen:
#   filename:  di.FetchResult.json
#   timestamp: 2026-09-13T00:17:45+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FetchResult(BaseModel):
    status: int = Field(..., title='Status')
    body: str = Field(..., title='Body')
