# generated by datamodel-codegen:
#   filename:  di.FetchPayload.json
#   timestamp: 2026-09-13T00:17:45+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FetchPayload(BaseModel):
    url: str = Field('https://example.com', title='Url')
