# generated by datamodel-codegen:
#   filename:  failure.FlakyPayload.json
#   timestamp: 2026-09-13T00:17:45+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FlakyPayload(BaseModel):
    fail_count: int = Field(2, title='Fail Count')
