# generated by datamodel-codegen:
#   filename:  progress.FileProcessorPayload.json
#   timestamp: 2026-09-13T00:17:46+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class FileProcessorPayload(BaseModel):
    filename: str = Field('data.csv', title='Filename')
    rows: int = Field(1000, title='Rows')
