# generated by datamodel-codegen:
#   filename:  ratelimit.EmptyPayload.json
#   timestamp: 2026-09-13T00:17:47+00:00

from __future__ import annotations

from pydantic import BaseModel


class EmptyPayload(BaseModel):
    pass
