# generated by datamodel-codegen:
#   filename:  realworld.DigestEmailResult.json
#   timestamp: 2026-09-13T00:17:48+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DigestEmailResult(BaseModel):
    message_id: str = Field(..., title='Message Id')
    recipients: int = Field(..., title='Recipients')
    articles_included: int = Field(..., title='Articles Included')
