# generated by datamodel-codegen:
#   filename:  realworld.ThumbnailPayload.json
#   timestamp: 2026-09-13T00:17:49+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class ThumbnailPayload(BaseModel):
    image_url: str = Field(
        ..., description='Source image URL or path', title='Image Url'
    )
    width: conint(ge=1, le=2000) = Field(200, title='Width')
    height: conint(ge=1, le=2000) = Field(200, title='Height')
    format: str = Field(
        'webp', description='Output format: webp, jpeg, png', title='Format'
    )
