# generated by datamodel-codegen:
#   filename:  realworld.DigestEmailPayload.json
#   timestamp: 2026-09-13T00:17:48+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class DigestEmailPayload(BaseModel):
    user_id: str = Field(..., description='User identifier', title='User Id')
    email: str = Field(..., description='Recipient email address', title='Email')
    period: str = Field(
        'weekly', description='Digest period: daily, weekly, monthly', title='Period'
    )
