# generated by datamodel-codegen:
#   filename:  realworld.CsvUploadPayload.json
#   timestamp: 2026-09-13T00:17:47+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class CsvUploadPayload(BaseModel):
    filename: str = Field(
        ..., description='Name of the uploaded CSV file', title='Filename'
    )
    row_count: conint(ge=1, le=100000) = Field(
        1000, description='Number of rows to process', title='Row Count'
    )
    chunk_size: conint(ge=100, le=5000) = Field(
        500, description='Rows per chunk', title='Chunk Size'
    )
