# generated by datamodel-codegen:
#   filename:  realworld.CsvChunkPayload.json
#   timestamp: 2026-09-13T00:17:47+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class CsvChunkPayload(BaseModel):
    filename: str = Field(..., title='Filename')
    chunk_id: int = Field(..., title='Chunk Id')
    start_row: int = Field(..., title='Start Row')
    end_row: int = Field(..., title='End Row')
