# generated by datamodel-codegen:
#   filename:  sync_demo.WordCountPayload.json
#   timestamp: 2026-09-13T00:17:49+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class WordCountPayload(BaseModel):
    text: str = Field(
        'TaskQ makes background jobs simple and reliable',
        description='Text to count words in',
        title='Text',
    )
