# generated by datamodel-codegen:
#   filename:  synthetic.DatetimePayload.json
#   timestamp: 2026-09-13T00:17:50+00:00

from __future__ import annotations

from datetime import date

from pydantic import AwareDatetime, BaseModel, Field


class DatetimePayload(BaseModel):
    started_at: AwareDatetime | None = Field(None, title='Started At')
    due_date: date = Field('2026-12-31', title='Due Date')
