# generated by datamodel-codegen:
#   filename:  synthetic.UnionPayload.json
#   timestamp: 2026-09-13T00:17:51+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class UnionPayload(BaseModel):
    value: int | str = Field(..., title='Value')
    maybe: float | None = Field(None, title='Maybe')
