# generated by datamodel-codegen:
#   filename:  synthetic.NestedPayload.json
#   timestamp: 2026-09-13T00:17:51+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class Address(BaseModel):
    street: str = Field(..., title='Street')
    city: str = Field(..., title='City')
    zip_code: constr(pattern=r'^\d{5}$') = Field(..., title='Zip Code')


class NestedPayload(BaseModel):
    address: Address
    tags: list[str] | None = Field(None, title='Tags')
