# generated by datamodel-codegen:
#   filename:  tags_demo.TaggedResult.json
#   timestamp: 2026-09-13T00:17:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TaggedResult(BaseModel):
    label: str = Field(..., title='Label')
    reversed: str = Field(..., title='Reversed')
