# generated by datamodel-codegen:
#   filename:  tags_demo.TaggedPayload.json
#   timestamp: 2026-09-13T00:17:52+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TaggedPayload(BaseModel):
    label: str = Field('demo', title='Label')
