# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-13T00:18:47+00:00

from __future__ import annotations

from datetime import date
from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class BatchCounterPayload(BaseModel):
    n: conint(ge=1, le=1000) | None = Field(
        5, description='Number of child jobs', title='N'
    )
    steps: conint(ge=1, le=1000) | None = Field(
        5, description='Steps per child', title='Steps'
    )


class BatchFinalizerPayload(BaseModel):
    batch_id: UUID = Field(..., title='Batch Id')
    expected: int = Field(..., title='Expected')


class EmptyPayload(BaseModel):
    pass


class WordCountPayload(BaseModel):
    text: str | None = Field(
        'TaskQ makes background jobs simple and reliable',
        description='Text to count words in',
        title='Text',
    )


class WordCountResult(BaseModel):
    word_count: int = Field(..., title='Word Count')
    char_count: int = Field(..., title='Char Count')
    processed_at: str | None = Field(None, title='Processed At')


class CounterPayload(BaseModel):
    n: int | None = Field(10, title='N')


class DbLookupPayload(BaseModel):
    item_id: int | None = Field(1, title='Item Id')


class DeduplicatedPayload(BaseModel):
    key: str | None = Field('default', title='Key')


class DeferredPayload(BaseModel):
    delay_seconds: int | None = Field(30, title='Delay Seconds')


class FanOutPayload(BaseModel):
    items: list[str] | None = Field(['a', 'b', 'c'], title='Items')


class FetchPayload(BaseModel):
    url: str | None = Field('https://example.com', title='Url')


class FetchResult(BaseModel):
    status: int = Field(..., title='Status')
    body: str = Field(..., title='Body')


class FileProcessorPayload(BaseModel):
    filename: str | None = Field('data.csv', title='Filename')
    rows: int | None = Field(1000, title='Rows')


class FlakyPayload(BaseModel):
    fail_count: int | None = Field(2, title='Fail Count')


class ThumbnailPayload(BaseModel):
    image_url: str = Field(
        ..., description='Source image URL or path', title='Image Url'
    )
    width: conint(ge=1, le=2000) | None = Field(200, title='Width')
    height: conint(ge=1, le=2000) | None = Field(200, title='Height')
    format: str | None = Field(
        'webp', description='Output format: webp, jpeg, png', title='Format'
    )


class ThumbnailResult(BaseModel):
    output_path: str = Field(..., title='Output Path')
    width: int = Field(..., title='Width')
    height: int = Field(..., title='Height')
    format: str = Field(..., title='Format')
    source_bytes: int = Field(..., title='Source Bytes')


class CsvChunkPayload(BaseModel):
    filename: str = Field(..., title='Filename')
    chunk_id: int = Field(..., title='Chunk Id')
    start_row: int = Field(..., title='Start Row')
    end_row: int = Field(..., title='End Row')


class CsvUploadPayload(BaseModel):
    filename: str = Field(
        ..., description='Name of the uploaded CSV file', title='Filename'
    )
    row_count: conint(ge=1, le=100000) | None = Field(
        1000, description='Number of rows to process', title='Row Count'
    )
    chunk_size: conint(ge=100, le=5000) | None = Field(
        500, description='Rows per chunk', title='Chunk Size'
    )


class DigestEmailPayload(BaseModel):
    user_id: str = Field(..., description='User identifier', title='User Id')
    email: str = Field(..., description='Recipient email address', title='Email')
    period: str | None = Field(
        'weekly', description='Digest period: daily, weekly, monthly', title='Period'
    )


class DigestEmailResult(BaseModel):
    message_id: str = Field(..., title='Message Id')
    recipients: int = Field(..., title='Recipients')
    articles_included: int = Field(..., title='Articles Included')


class SnoozePayload(BaseModel):
    delay_seconds: int | None = Field(10, title='Delay Seconds')
    wake_after_attempt: int | None = Field(1, title='Wake After Attempt')


class PipelinePayload(BaseModel):
    text: str | None = Field('hello', title='Text')


class StepTwoPayload(BaseModel):
    processed: str = Field(..., title='Processed')


class SumPayload(BaseModel):
    values: str | None = Field('1,2,3', title='Values')


class SumResult(BaseModel):
    total: int = Field(..., title='Total')


class TaggedPayload(BaseModel):
    label: str | None = Field('demo', title='Label')


class TaggedResult(BaseModel):
    label: str = Field(..., title='Label')
    reversed: str = Field(..., title='Reversed')


class TickerPayload(BaseModel):
    pass


class Priority(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class EnumPayload(BaseModel):
    priority: Priority | None = 'medium'


class ConstrainedStringPayload(BaseModel):
    slug: constr(min_length=3, max_length=20) = Field(..., title='Slug')
    label: constr(pattern=r'^[a-z]+$') | None = Field('task', title='Label')


class Address(BaseModel):
    street: str = Field(..., title='Street')
    city: str = Field(..., title='City')
    zip_code: constr(pattern=r'^\d{5}$') = Field(..., title='Zip Code')


class NestedPayload(BaseModel):
    address: Address
    tags: list[str] | None = Field(None, title='Tags')


class UnionPayload(BaseModel):
    value: int | str = Field(..., title='Value')
    maybe: float | None = Field(None, title='Maybe')


class DatetimePayload(BaseModel):
    started_at: AwareDatetime | None = Field(None, title='Started At')
    due_date: date | None = Field('2026-12-31', title='Due Date')
