"""TaskQ: async-native, Postgres-backed background job library.

Canonical imports:

    from taskq import actor, TaskQ, JobHandle, JobFailed, RetryPolicy
    from taskq import cron, ScheduleHandle
    from taskq.context import JobContext
    from taskq.di import ProviderRegistry, Scope
"""

import importlib.metadata

from taskq.actor import ActorFn, ActorFnWithCtx, ActorHandler, ActorRef, actor
from taskq.actor_config_ops import ActorConfigRow, DeregisterResult
from taskq.auth import (
    PgCredential,
    PgCredentialProvider,
    RedisCredential,
    RedisCredentialProvider,
    enrich_pg_dsn,
    make_dedicated_conn_factory,
    make_pg_pool_factory,
    make_redis_client_factory,
)
from taskq.backend._protocol import (
    Backend,
    BatchCounts,
    BatchFilter,
    BatchRow,
    CancelPhase,
    DstStrategy,
    EventRow,
    IdempotencyKey,
    IdentityKey,
    JobFilter,
    JobId,
    JobPage,
    JobRow,
    JobSortField,
    QueueMode,
    QueueName,
    RateLimitBackend,
    RetryKind,
    ScheduleRecord,
)
from taskq.backend.clock import Clock, SystemClock
from taskq.batch import (
    BatchCompletionStatus,
    BatchHandle,
    BatchSummary,
    EnqueueItem,
    apply_batch_terminal_outcome,
    wait_for_batch,
)
from taskq.batch_policy import AbortBatchAfter, BatchFailurePolicy
from taskq.client import BulkCancelResult, CancelResult, JobEvent, JobHandle, JobsClient, TaskQ
from taskq.client._actors import ActorsClient
from taskq.client._enqueuer import SubJobEnqueuer
from taskq.connections import ConnFactory, PoolFactory, RedisFactory, WorkerConnections
from taskq.context import JobContext
from taskq.cron import CronScheduleSpec, ScheduleHandle, cron
from taskq.exceptions import (
    ActorConfigDriftError,
    ActorConfigDriftList,
    ActorDeregistrationError,
    ActorHasActiveJobsError,
    ActorHasEnabledSchedulesError,
    ActorNotFoundError,
    BackpressureError,
    BatchAbortedError,
    DependencyCycle,
    DIError,
    EmptyBatchError,
    EmptyFilterError,
    IllegalStateTransition,
    JobFailed,
    MaxPendingExceededError,
    MissingProvider,
    PartialBatchError,
    PayloadValidationError,
    ProgressTooLarge,
    ReservationUnavailable,
    ResultTooLarge,
    ResultUnavailable,
    RetryAfter,
    SchemaNotMigratedError,
    ScopedIdempotencyMigrationPendingError,
    ScopeViolation,
    SingletonCollisionError,
    Snooze,
    SubEnqueueError,
    TaskQError,
    WorkerOwnershipMismatch,
    validate_actor_payload,
)
from taskq.obs import ErrorReporter, NullErrorReporter
from taskq.progress import ProgressEvent
from taskq.retry import (
    Fail,
    JobRetryState,
    OnSuccess,
    Retry,
    RetryClassifier,
    RetryClassifierHook,
    RetryDecision,
    RetryOverride,
    RetryPolicy,
)
from taskq.scheduler import register_cron
from taskq.settings import OIDCSettings, SAMLSettings, TaskQSettings, WorkerSettings
from taskq.testing.clock import FakeClock

__all__ = [
    "AbortBatchAfter",
    "ActorConfigDriftError",
    "ActorConfigDriftList",
    "ActorConfigRow",
    "ActorDeregistrationError",
    "ActorFn",
    "ActorFnWithCtx",
    "ActorHandler",
    "ActorHasActiveJobsError",
    "ActorHasEnabledSchedulesError",
    "ActorNotFoundError",
    "ActorRef",
    "ActorsClient",
    "Backend",
    "BackpressureError",
    "BatchAbortedError",
    "BatchCompletionStatus",
    "BatchCounts",
    "BatchFailurePolicy",
    "BatchFilter",
    "BatchHandle",
    "BatchRow",
    "BatchSummary",
    "BulkCancelResult",
    "CancelPhase",
    "CancelResult",
    "Clock",
    "ConnFactory",
    "CronScheduleSpec",
    "DIError",
    "DependencyCycle",
    "DeregisterResult",
    "DstStrategy",
    "EmptyBatchError",
    "EmptyFilterError",
    "EnqueueItem",
    "ErrorReporter",
    "EventRow",
    "Fail",
    "FakeClock",
    "IdempotencyKey",
    "IdentityKey",
    "IllegalStateTransition",
    "JobContext",
    "JobEvent",
    "JobFailed",
    "JobFilter",
    "JobHandle",
    "JobId",
    "JobPage",
    "JobRetryState",
    "JobRow",
    "JobSortField",
    "JobsClient",
    "MaxPendingExceededError",
    "MissingProvider",
    "NullErrorReporter",
    "OIDCSettings",
    "OnSuccess",
    "PartialBatchError",
    "PayloadValidationError",
    "PgCredential",
    "PgCredentialProvider",
    "PoolFactory",
    "ProgressEvent",
    "ProgressTooLarge",
    "QueueMode",
    "QueueName",
    "RateLimitBackend",
    "RedisCredential",
    "RedisCredentialProvider",
    "RedisFactory",
    "ReservationUnavailable",
    "ResultTooLarge",
    "ResultUnavailable",
    "Retry",
    "RetryAfter",
    "RetryClassifier",
    "RetryClassifierHook",
    "RetryDecision",
    "RetryKind",
    "RetryOverride",
    "RetryPolicy",
    "SAMLSettings",
    "ScheduleHandle",
    "ScheduleRecord",
    "SchemaNotMigratedError",
    "ScopeViolation",
    "ScopedIdempotencyMigrationPendingError",
    "SingletonCollisionError",
    "Snooze",
    "SubEnqueueError",
    "SubJobEnqueuer",
    "SystemClock",
    "TaskQ",
    "TaskQError",
    "TaskQSettings",
    "WorkerConnections",
    "WorkerOwnershipMismatch",
    "WorkerSettings",
    "__version__",
    "actor",
    "apply_batch_terminal_outcome",
    "cron",
    "enrich_pg_dsn",
    "make_dedicated_conn_factory",
    "make_pg_pool_factory",
    "make_redis_client_factory",
    "register_cron",
    "validate_actor_payload",
    "wait_for_batch",
]

try:
    __version__ = importlib.metadata.version("taskq-py")
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.2.2"  # x-release-please-version
