# generated by datamodel-codegen:
#   filename:  schemas.generated.json

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, RootModel, conint, constr


class Model(RootModel[Any]):
    root: Any


class Locale(Enum):
    en = 'en'
    de = 'de'
    fr = 'fr'


class SendWelcomeEmailPayload(BaseModel):
    userId: UUID
    email: EmailStr
    locale: Locale = 'en'


class SendWelcomeEmailResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messageId: str
    acceptedAt: str


class Format(Enum):
    webp = 'webp'
    avif = 'avif'
    jpeg = 'jpeg'


class ResizeImagePayload(BaseModel):
    objectKey: constr(min_length=1)
    width: conint(le=8192, gt=0)
    format: Format


class ResizeImageResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    objectKey: str
    bytes: conint(ge=-9007199254740991, le=9007199254740991)
    width: conint(ge=-9007199254740991, le=9007199254740991)
